### ISSUE TITLE
The lable 'in the menu on the left' and 'in the browser tab title' seems not correct

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit-podman#1051]
Cockpit version: cockpit-272-1.fc36.x86_64
Cockpit-podman version: cockpit-podman-50-1.fc36.noarch
Podman version: podman-4.1.1-2.fc36.x86_64
OS: Fedora 36

Issue description
The lable 'in the menu on the left' and 'in the browser tab title' is 'Podman containers' for now, but maybe it should be 'Podman Containers'

Steps to reproduce
1. Install cockpit-podman, then log in cockpit
2. Check the label 'in the menu on the left' and 'in the browser tab title' of the podman page

Actual result
1 After step 2, the label is 'Podman containers', but maybe it should be 'Podman Containers'

![label](https://user-images.githubusercontent.com/25657472/180472261-57e38695-4ae3-4daf-8684-678c6d419191.png)

**Comment by marusak** [comment]
We don't use capital case anywhere - except page names. So I think you might be correct, let's just confirm with @garrett

**Comment by garrett** [comment]
Firstly: Thanks for reporting!

From https://www.patternfly.org/v4/ux-writing/capitalization/#capitalization-across-patternfly:

> Follow these guidelines for **PatternFly content**, including documentation, UX copy, blog articles, and more.
> 
> - Use **sentence case** for _page titles_, menu items, _navigation items_, headings, subtitles, and subheadings across PatternFly.
>     
> - Capitalize proper nouns, product names, acronyms, and initialisms.
>     
> - Write all components in **lowercase** unless they start a sentence.
>     
>     Example: "Card, button, and banner components are my favorites."

Note that they do mention sentence case specifically for page titles and navigation items (among everything else).

...But, to make it confusing, they also add:

> On _PatternFly's website_, all navigation items, button text, and headings are written in sentence case

:shrug: But then if you look at the website's navigation, it's still sentence case. So I think Title Case is deprecated there too. (I clearly remember it being an (odd) exception a while back, so I guess they changed it at some point where even navigation items.)

We need to flip this issue around and fix the usages of Title Case in the navigation in the rest of Cockpit.

**Comment by garrett** [comment]
Filed @ https://github.com/cockpit-project/cockpit/issues/17590; I've made pending PRs for Cockpit and Machines
