### ISSUE TITLE
Create container's integration tab is missing style for the host path dropdown

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#1054]
As seen @ https://github.com/cockpit-project/cockpit-podman/pull/1017#issuecomment-1189984601:

> The "host path" in the "create container" dialog looks totally broken
>
> ![](https://raw.githubusercontent.com/cockpit-project/pixel-test-reference/c0c3aa946db6c0698ada1fbeee42f5c24e8aa5c9/TestApplication-testRunImageSystem-integration-pixels.png)

**Comment by garrett** [comment]
Is this still a bug?

Here's what I see on a local build:

![image](https://user-images.githubusercontent.com/10246/180764596-e2b2b414-3831-497d-b903-bc2fe62afb8b.png)

**Comment by marusak** [comment]
I was playing with this for some time now, I just sent https://github.com/cockpit-project/cockpit-podman/pull/1056

> Is this still a bug?

It is, but you need to put there longer input so it start to overflow

**Comment by garrett** [comment]
As mentioned on IRC:

The problem is CSS rewriting in our production step.

The tool we're using is an old version and needs to be updated. The new version may still have some issues, but it looks like it at least fixes this outline problem.
