### ISSUE TITLE
Improve spacing in the integration tab of the create container dialog

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#1055]
Problem areas are marked in orange:

![image](https://user-images.githubusercontent.com/10246/180761601-524bcbc6-c7c3-43c0-ae15-2b9ff4f9816b.png)

Having this extra space removes much needed space from the network and volumes sections, as some of the fields are too short otherwise.

**Comment by marusak** [comment]
Just by correctly calculating the spacing it looks like this:

![Screenshot from 2022-07-25 14-04-38](https://user-images.githubusercontent.com/12330670/180773933-fe1d6591-d0e9-4b9f-81f7-c6b9fab26420.png)

Removing the spacing on left is bit triciker - we are using [field groups](https://www.patternfly.org/v4/components/form#field-groups) which set this spacing. Nothing else provides options to add buttons on the title line ( those `[Add ...]` buttons). However it is one css line that needs to be manually changed:

![Screenshot from 2022-07-25 14-05-25](https://user-images.githubusercontent.com/12330670/180774257-4730fc78-7487-4716-a1f4-d1c83fce06e3.png)

Should I go with the second option and manually change the rule?
