### ISSUE TITLE
Podman User Service is not detected when running

### ISSUE THREAD

**Issue by digitalpardoe** [cockpit-project/cockpit-podman#1085]
Cockpit version: 264-1
Cockpit-podman version: 45-1
Podman version: 3.4.4+ds1-1ubuntu1
OS: Ubuntu Server 22.04.1 LTS

cockpit-podman doesn't seem to be aware of the user service running so the "User Podman service is also available" banner is always displayed and none of the user-service specific options are available.

Cockpit itself seems to be aware of the service running:

<img width="490" alt="Screenshot 2022-08-26 at 10 31 48" src="https://user-images.githubusercontent.com/29490/186874670-4e62769c-cee1-4fed-93bb-c0198c7c7ebe.png">

And the output of `systemctl` seems to indicate that it is:

```
user@server:~$ systemctl --user status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-08-26 09:22:50 UTC; 8min ago
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/user/1000/podman/podman.sock (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket
```

There aren't errors shown in the JS console or any logs that I'm aware of the location of.

When I click the "Start" button nothing happens and the banner remains however the output in the JS console is:

```
[Log] SyntaxError: JSON Parse error: Unexpected EOF (index.js, line 2)
parse
(anonymous function) — index.js:2:1457746
promiseReactionJob

[Log] re (cockpit.js, line 1)
message: "Unknown interface 'org.freedesktop.systemd1.Service'."
name: "org.freedesktop.DBus.Error.UnknownInterface"
problem: null
toString: function()
re Prototype
constructor: function(e,t)
Object Prototype
```

There aren't any particular steps to reproduce, this was a clean install of Ubuntu Server 20.04 that I had installed `cockpit` on (but not `cockpit-podman`) and then immediately updated to Ubuntu Server 21.04 and installed `cockpit-podman` on.

**Comment by marusak** [comment]
I have to guesses, either https://github.com/cockpit-project/cockpit-podman/issues/1025 or https://github.com/containers/podman/issues/8751

How many containers and images do you have?

Can you run `curl --unix-socket /run/user/1000/podman/podman.sock http://d/v1.24/events` and let it run and then in different terminal do some podman action (for example `podman run`). Do you see events coming in? Does it stay open indefinitely?

**Comment by digitalpardoe** [comment]
@marusak This was with 0 images and 0 containers set up, however even when adding containers I still had the error.

Interestingly I'd decided to go with Docker instead so had uninstalled `podman` and `cockpit-podman` completely (something I'd tried a few times to fix this anyway with little success) however, after re-installing it to test your suggestions it appears to be working correctly - I'm not sure if the Docker installation has maybe done something with permissions somewhere that has made it function correctly?

As for your debugging step with `curl` - that appears to be working as expected, which is expected I guess as `cockpit-podman` now seems to be working correctly too.

I'll close this issue for now as it's no longer an issue, if I come across it again I'll re-open it.
