### ISSUE TITLE
Prune containers

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#1099]
We should add an action menu with actions, similar to [the mockup](https://user-images.githubusercontent.com/10246/124738736-8694b080-df19-11eb-91e3-dae599569683.png). (See container context menu on the side.)

One of the first items should be to prune containers, which is `podman container prune`.

An acceptable first pass would be to have the prune action using Podman's command (above) and list the containers to be removed in the dialog, in a list, with an "all or nothing" approach.

A better version, which could either be the first pass (if you're ambitious) or an eventual follow-up, would be to have the same UI, but allow the user to unselect individual containers. The backend part to remove the not-running containers (that are selected in the modal dialog) would be implemented differently, however.

We have something similar already, with image pruning. This would basically be the same thing, but for containers.

**Comment by jelly** [comment]
For the pruning of unused images we check if there are used by a container, what would be the logic for the pruning of containers? From some testing it seems to be all non-running containers?

**Comment by jelly** [comment]
![image](https://user-images.githubusercontent.com/67428/225584487-73de773e-c713-4843-aca9-86d6221a89b0.png)

Work in progress, so our listing table can sort! So we should really implement sorting now also in the Containers/Images view.

The text probably needs some adjustment and the selection options are obviously missing, I'll figure out if we can do a select all with our current component.

**Comment by garrett** [comment]
> I think we should select all containers by default.

All visible containers — but those should not include containers that are running.

**Comment by jelly** [comment]
> > I think we should select all containers by default.
> 
> All visible containers — but those should not include containers that are running.

Right, the shown list is already all non running containers and not containers part of pods. I've excluded pods entirely as that requires some more thought and maybe something for a follow up.

**Comment by jelly** [comment]
Fixed in https://github.com/cockpit-project/cockpit-podman/pull/1235
