### ISSUE TITLE
Create Container In Pod does not respect the "command" of the image.

### ISSUE THREAD

**Issue by srbaker** [cockpit-project/cockpit-podman#1126]
Cockpit version: 278
Cockpit-podman version: 55
Podman version: 4.2.1
OS: Fedora Server 36

When I click "Create container", the command defaults to `sh`.  I think it should default to the "command" option of the image you're using.

Demonstration: if you have the postgres default image installed from docker.io/library/postgres:latest, when you click Create container in the Containers section, the Command is `sh` not `postgres`.

**Comment by jelly** [comment]
Thanks for the report, we should also check this behaviour with the normal create container workflow.

**Comment by jelly** [comment]
Same issue occurs for when I try to create a new container for example using the redis image, we launch it with `sh` instead of the default Command.
