### ISSUE TITLE
Change environment-variables

### ISSUE THREAD

**Issue by st0nec0ld** [cockpit-project/cockpit-podman#1139]
hey guys, i`m new at cockpit podman and want to change the environment variables.

Example, is succesfull create a pod for sabnzbd with environment "TZ=Europe/London". Now i want to change that to "TZ=Europe/Berlin" or change the port from 8080:8080 to 8080:8081.

how i can do that?

**Comment by jelly** [comment]
Containers/pods are not meant to be changed once they are started like virtual machines and we don't support a re-create https://github.com/cockpit-project/cockpit-podman/issues/363 option at the moment. So unfortunately you will have to re-create the pod.

You could consider saving the current pod with `podman kube generate` as a Kubernetes Pod (yaml file) and then changing the environment variables there and re-creating the pod using `podman kube play`.

https://www.redhat.com/sysadmin/podman-play-kube-updates
