### ISSUE TITLE
Python bridge support

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-podman#1189]
```
warning: watching is not implemented, use fswatch1
```

![image](https://user-images.githubusercontent.com/67428/213750235-61422348-a180-4b9c-b222-287e9c9c6b67.png)

This is from the `FileAutoComplete` component from Cockpit.

Allowed Messages needs to be extended with:
```
asyncio-ERROR: Task was destroyed but it is pending!
```

**Comment by martinpitt** [comment]
@jelly: Fixed in https://github.com/cockpit-project/cockpit/commit/a3fad8f6e710375391d6e5a5da350e81ec11813d , we just need to bump the cockpit import.
