### ISSUE TITLE
'await' unexpected reserved word

### ISSUE THREAD

**Issue by dikleins** [cockpit-project/cockpit-podman#1269]
Cockpit version: 287-1~bpo22.04.1
Cockpit-podman version: clone of master
Podman version: 3.4.4
OS: Ubuntu 22.04

After clone of current version and calling 'make' (as documented on Github) the following error occurs:
......./build.js:32
const context = await esbuild.context({
                            ^^^^^

SyntaxError: Unexpected reserved word

**Comment by martinpitt** [comment]
Unfortunately Ubuntu 22.04's [nodejs](https://launchpad.net/ubuntu/+source/nodejs) version is very old (12), that version does not yet support top-level `await`. Please either [use our official development container in toolbox](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#setting-up-development-container) (prefered), or install a newer node through [n](https://www.npmjs.com/package/n), update to a newer Ubuntu, or find some backport.

**Comment by dpieski** [comment]
I got here from realizing that Ubuntu `cockpit-podman` was version 45 while the most recent release was 80.

For anyone else, you can use the Ubuntu backports to install `cockpit-podman`.

First, make sure you know the name of your Ubuntu with `lsb_release -cs`
Then install with `sudo apt install cockpit-podman/name-backports`, so for `jammy` it would be `sudo apt install cockpit-podman/jammy-backports`

Refresh the page and the Podman Containers page will be updated.
