### ISSUE TITLE
--device arguments

### ISSUE THREAD

**Issue by caioolivv** [cockpit-project/cockpit-podman#1276]
From what I've seen on Issues #544 and #728, there is no possible way to add --device arguments. Is this right? If so, is there any workaround or any plans on supporting this?

**Comment by marusak** [comment]
Unfortunately there is no workaround from our UI. Only solution at this moment is to use commandline.
Regarding plans - This is not on the teams current priority list however we are happy to accept any contributions :)

Closing as duplicate of #544
