### ISSUE TITLE
Problem with podman Containers and Images lists

### ISSUE THREAD

**Issue by velezd** [cockpit-project/cockpit-podman#128]
Version: cockpit-196-1.fc30, cockpit-podman-2-1.fc30, podman-1.4.0-2.fc30

The list of Containers and Images doesn't update when image/container is added/removed, whole page has to be reloaded.
This issue doesn't occur in the first session after start or restart of io.cockpit.socket, so maybe it's problem in podman.

Steps to reproduce
1. Start/restart io.cockpit.socket
2. Login to cockpit
3. Open Podman Containers
4. Download some image and create container
5. Delete container and image
6. Logout and repeat from step 2
Doing it second time you will have to hit F5 to see the new image and container in the list.

**Comment by martinpitt** [comment]
This does work in general, but current podman 1.3 and 1.4 versions are unfortunately rather prone to crashes. If that happens, can you please check `journalctl` for a podman crash?

**Comment by marusak** [comment]
No reply for some time and new podman should be much more stable.
