### ISSUE TITLE
Unknown interface 'org.freedesktop.systemd1.Service'.

### ISSUE THREAD

**Issue by LiaraAlis** [cockpit-project/cockpit-podman#1298]
Cockpit version: 287-1~bpo11+1
Cockpit-podman version: 65-1~bpo11+1
Podman version: 4.5.1
OS: Debian 11 (bullseye)

Hello together!

I found cockpit a few days ago and liked it at the first view. My plan is to run cockpit and dockerize my different projects/websites. As I saw, podman is the current solution for cockpit. Unfortunately, from my point of view, podman is absolutely unusable with Debian 11. I ran from one bug into another, especially with podman-compose and running container with writeable volumes. Because I have seen that the most bugs should fixed in newer versions of podman, I setup the alvistack repository and installed Podman 4.5.1.

But now, after I reinstalled the whole server, when opening podman view in cockpit, the message `User Podman service is also available` appears. Clicking on `start` results in an error message in the console:
```
re {problem: null, name: 'org.freedesktop.DBus.Error.UnknownInterface', message: "Unknown interface 'org.freedesktop.systemd1.Service'.", toString: ƒ}
```

I'm very frustrated and don't know what to do. I want a stable up and running system and I've been sitting on this for far too long. I'm thinking about switching to a regular control panel maybe with a container management tool. But I really like cockpit and want to use it.

Has anyone similar experience or can give me tips what the problem here is?

**Comment by martinpitt** [comment]
Indeed, user containers are a bit brittle in Debian 11 still. System containers ought to work, though. We also test cockpit-podman on Debian 11, but our test VMs have these packages installed. But not explicitly, they are dependencies (rather "Recommends:") of podman. So it seems you disabled recommends in apt at least when you installed podman?

**Comment by martinpitt** [comment]
Oh, "alvistack repository" -- yes, that's not Debian itself, it probably misses these dependencies. Glad you figured it out!

**Comment by LiaraAlis** [comment]
@martinpitt Thanks for your feedback. It seems that it works good now. Podman 4 from alvistack seems to be much more stable as all other stable packages from the debian repository. 😅
But yes, the dependencies are a little bit tricky. I hope I can use this setup now…
