### ISSUE TITLE
Bug - Popover in Create container dialog is broken

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-podman#1302]
Cockpit version: 292
Cockpit-podman version: 70
Podman version: 4.5.0
OS: Fedora Workstation 38

![image](https://github.com/cockpit-project/cockpit-podman/assets/108616679/6904c2d1-077b-44d4-b283-57e93acd0d69)

**Comment by jelly** [comment]
With the PF5 update this has been fixed

![image](https://github.com/cockpit-project/cockpit-podman/assets/67428/d9bf649c-b89b-4cb7-b73e-274598e00430)
