### ISSUE TITLE
Screen Width for Podman Containers list 

### ISSUE THREAD

**Issue by shawnbure** [cockpit-project/cockpit-podman#1319]
Cockpit version: 294.1
Cockpit-podman version: 71
Podman version: podman version 4.5.1
OS: Fedora Server 38

Podman Containers screen is wider than the overall app width. This makes the containers list run off the screen to the right. No scrollbars are present and one must select text and drag the screen to the right to see the container commands list. This happens in Safari and Chrome.

Steps to reproduce

1. Create a container with a very long command.
2. Observe container list that is too wide.
3. Example command is a Cloudflared Tunnel (then has been purposely changed to invalid but same length):
4. tunnel --no-autoupdate run --token eyJhIjoiNsdfsdfsfdsdffmYTk4YzZlNDA3MWIasdfadcdsfsdfsfsddsverlYmZhMjgtZDMyMSsdfsfdZGUxYWNlOGQyIiwicyI6Ik9UTmlfsdfssdfsfsdfTm1NM0xUaGhNelV0WVRKa05XWmxNVsdfsfsfsdfsdfsfsdfsdsdfsdfdfsfsdfsfsdfsdfsdfsdfsdsdsdf

![image](https://github.com/cockpit-project/cockpit-podman/assets/4427703/7365e2fe-929c-4ca1-b0bc-1b771b2bf852)

**Comment by martinpitt** [comment]
I can reproduce this, but not quite like you. For wide screens, it always works fine for me, even with long commands (as toolbox produces). E.g.

![image](https://github.com/cockpit-project/cockpit-podman/assets/200109/89f04faf-6275-49fc-b79c-fb2d4ff1ced8)

I do get the effect on narrow widths:

![image](https://github.com/cockpit-project/cockpit-podman/assets/200109/c83f199d-556f-48bc-beb1-554d291e4b43)

I tested @shubhit7 's [initial proposed fix](https://github.com/shubhit7/cockpit-podman/commit/b8a1afadb0fb8c54d11107fe65a79df7c08d7337), and that does not change the bug for me.

**Comment by shubhit7** [comment]
@martinpitt 
Try creating a container, maybe using your busybox image and enter the following in the command field:

"tunnel --no-autoupdate run --token eyJhIjoiNsdfsdfsfdsdffmYTk4YzZlNDA3MWIasdfadcdsfsdfsfsddsverlYmZhMjgtZDMyMSsdfsfdZGUxYWNlOGQyIiwicyI6Ik9UTmlfsdfssdfsfsdfTm1NM0xUaGhNelV0WVRKa05XWmxNVsdfsfsfsdfsdfsfsdfsdsdfsdfdfsfsdfsfsdfsdfsdfsdfsdsdsdf" 

You should be able to reproduce the issue same way.
Idea is to test it with very long single word (no spaces). We can also add long name in the container name section, and issue can be seen even on large screens.

My commit fixes this.

I guess, what you are seeing on the smaller screen is actually not related to long names rather it is an issue with patternfly and it persists even with smaller names. Will have a look on this issue as well.

**Comment by martinpitt** [comment]
Indeed, thanks! Reproduced with

```sh
podman run -it --rm registry.fedoraproject.org/fedora:rawhide sh -c 'echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; sleep infinity'
```

**Comment by shawnbure** [comment]
Is there a way I can test? Any instructions - I see the commit but I have no clue where to Make that change on my system. I was thinking I can manually change the podman.scss file?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by martinpitt** [comment]
@shawnbure : You can install this COPR to test: https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-podman-1357/ . Next Wednesday we'll do a new release into Fedora proper.

**Comment by shawnbure** [comment]
Confirmed fix!!!

Amazing work guys - I really thought I was submitting an issue to a 
black hole :)

What is cockpit written in? I was a professional software engineer for 
a bunch of years until I left and started my own company. Sometimes I 
miss it!!!

**Comment by martinpitt** [comment]
@shawnbure : The web parts in HTML, CSS, and JavaScript, the "engine" in Python and C, tests in Python.
