### ISSUE TITLE
Create container field groups should use trash icons, not a secondary button with a minus

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#1382]
PF field groups are supposed to use a trash icon.

Reference: https://www.patternfly.org/components/forms/form/#field-groups

![image](https://github.com/cockpit-project/cockpit-podman/assets/10246/51e2be8c-b4b9-4c5d-970d-3a896d03e2ba)

Currently:

![image](https://github.com/cockpit-project/cockpit-podman/assets/10246/89e173ae-0bb5-4143-9da4-7188fbc22d69)

As seen @ https://github.com/cockpit-project/cockpit/pull/19024#issuecomment-1686190998

**Comment by subhoghoshX** [comment]
It appears to have been fixed in #1375. Can be closed.

**Comment by martinpitt** [comment]
Nice, thanks @subhoghoshX for checking!
