### ISSUE TITLE
Fix error handling

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-podman#14]
In utils.js `handleVarlinkCallError()`, don't stringify the error, but return it as-is, so that callers can handle different kinds of errors differently. There could be a separate util method to stringify an error for logging or showing to the user, of course.

**Comment by marusak** [comment]
@martinpitt can you elaborate what exactly is this issue about?
If it is about returning caller the error not as string, but as object, than that is happening:
```js
.catch(ex => {                                                      
  handleVarlinkCallError(ex);                                     
  return Promise.reject(ex);                                      
});
```
`handleVarlinkCallError` only logs the error, and then the promise is rejected with the original error object, so callers can deal with it separately.

**Comment by martinpitt** [comment]
Oh nice, and now it's even just being used in one place. It isn't even exported any more. This was a lot more messy when I filed this, great to see that it got fixed now.
