### ISSUE TITLE
Details not showing when creating a container off an existing image (of different user) and crash

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-podman#1408]
Cockpit version: xxx
Cockpit-podman version: 76-7-g149fc4f
Podman version: 4.6.2
OS: fedora-38

[Screencast from 2023-09-14 15-09-08.webm](https://github.com/cockpit-project/cockpit-podman/assets/108616679/350d7b94-f243-4197-a504-13dc467e7495)

**Comment by jelly** [comment]
Can reproduce this with the tasks container, as it's a toolbox image maybe that's somehow special

**Comment by jelly** [comment]
Actually since this image is so big, it's more the Integration and other tabs which don't handle the downloading Status.
