### ISSUE TITLE
PF4 aligning

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#143]
There are some issues with the new PF4 look. I am opening this as issues tracker. (pretty sure that @garrett and @andreasn see many little details I don't see. These are just the biggest ones even I noticed :) )

TODO:

- [ ] Clicking on new image to be downloaded makes the field blue without any text (plus the search button is misaligned)
- [ ] Every plus sign in running image is of different size (and placeholders are cut from both sides?)
- [ ] Too much padding over containers and images on main page?

![Screenshot from 2019-07-11 07-02-26](https://user-images.githubusercontent.com/12330670/61023409-25798700-a3aa-11e9-90b2-d8aee486a5f6.png)

![Screenshot from 2019-07-11 07-05-27](https://user-images.githubusercontent.com/12330670/61023447-5a85d980-a3aa-11e9-9273-b524d94f1acc.png)

![Screenshot from 2019-07-11 07-09-53](https://user-images.githubusercontent.com/12330670/61023623-f879a400-a3aa-11e9-80f3-e55c39ec3d55.png)

**Comment by garrett** [comment]
Thanks for opening the issue! I'm finally getting around to this.

I'm guessing a lot of the fixes are going to be similar to what I had to change for Docker @ https://github.com/cockpit-project/cockpit/commit/8343a5f3caec7d7d3130d035f5d4c32f7a647128, as it also had similar issues.

**Comment by martinpitt** [comment]
These are all fixed by https://github.com/cockpit-project/cockpit-podman/pull/148

**Comment by martinpitt** [comment]
#148 landed, closing.
