### ISSUE TITLE
Nightly tests did not succeed on fedora-39/podman-next: containers-common 1-97 → 1-98 breaks images with multiple tags

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1474]
Tests failed on 3427ba6d5a0f03b4053fa883d42f5a9852bc1423, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231106-015344-3427ba6d-fedora-39-podman-next//log.html)

**Comment by martinpitt** [comment]
This is strange -- that's exactly the same failure as I just saw in https://github.com/containers/podman/pull/20595 , but that PR didn't land yet. So question is, did it break in podman-next or did that PR build somehow bleed into this run. At first sight, the latter doesn't seem to happen, the "dnf update"  list only shows "(Fedora) updates" and "podman-next".

**Comment by martinpitt** [comment]
This reproduces easily locally, with
```
TEST_OS=fedora-39 TEST_SCENARIO=podman-next make prepare-check
TEST_OS=fedora-39 TEST_SCENARIO=podman-next test/check-application TestApplication.testDownloadImage
```
So I figure this broke in podman-next, and https://github.com/containers/podman/pull/20595 was just the first place to spot that.

**Comment by jelly** [comment]
Nightly hasn't failed for over 4 days, so I assume this can be closed?

**Comment by martinpitt** [comment]
Right, this got worked around in PR #1477
