### ISSUE TITLE
panic: runtime error: slice bounds out of range on RHEL 8.1 beta when pulling container image

### ISSUE THREAD

**Issue by Sebastiaan76** [cockpit-project/cockpit-podman#155]
I'm getting a coredump which starts with a log entry of "panic: runtime error: slice bounds out of range".

Using/testing the recently release RHEL 8.1 beta.

This issue occurs whenever I try to pull an image via cockpit, either as a user, or as root.

trying to pull, for example, docker.io/library/couchbase via cockpit ui results in a coredump and SIGABRT of io.podman.service.

This does not happen if I do a "podman pull couchbase" from the command line ( which pulls the image without a problem ), so seems to be a cockpit-podman issue ( at least on the surface ) hence posting here. Or should I post at containers/libpod?

Also, if I do pull an image from the command line, when i log into Cockpit - I can't see that image ( which may, or may not be intended? )

Also, this is with Selinux in permissive mode.

Happy to provide more info/logs etc if it's helpful.

EDIT: Testing this on Fedora 30 - same thing. Podman version 1.4.4 on Fedora 30, and version 1.4.2 on RHEL 8.1

**Comment by marusak** [comment]
> Also, if I do pull an image from the command line, when i log into Cockpit - I can't see that image ( which may, or may not be intended? )

This is missing feature - you pulled (most likely) as non-root user, but cockpit-podman shows what root created/pulled. See #83 for more info.

Anyway, back to your issue. What cockpit-podman does is call podman API, which technically for your problem calls `sudo varlink call unix:/run/podman/io.podman/io.podman.PullImage '{ "name": "couchbase" }'`. Can you please test this in commandline and let me know if it fails in the same way?

Also I tested this on Fedora 30 and it worked for me just fine. Podman 1.4.4 as well.
Can you also please provide version of `cockpit-podman`.

**Comment by marusak** [comment]
@Sebastiaan76 ping?
