### ISSUE TITLE
Nightly tests did not succeed on arch

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1550]
Tests failed on c26d8da9a4678b2f378acb9de10a26c8e1d98111, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1549-20240207-080328-c26d8da9-arch/log.html)

**Comment by jelly** [comment]
Hahaha, the tests was still running while I merged the PR. Now that's a fun bug :)
