### ISSUE TITLE
Nightly tests did not succeed on fedora-39/podman-next: user containers fail to start without default route (passta regression)

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1595]
Tests failed on 232ea860e8b53e6177072154a6ed3d1eacc38c1f, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240301-015303-232ea860-fedora-39-podman-next/log.html)

**Comment by martinpitt** [comment]
Ugh, this is messy. This is fallout from https://github.com/containers/podman/pull/21563 . tmt tests are online, ours  are offline, and pasta doesn't get along with that. This needs urgent reporting.

**Comment by martinpitt** [comment]
Forwarded to https://github.com/containers/podman/issues/21896 .
