### ISSUE TITLE
Removing Environment variables when creating a container breaks validation

### ISSUE THREAD

**Issue by Tiefseetauchner** [cockpit-project/cockpit-podman#1619]
Cockpit version: 312-1
Cockpit-podman version: 84.1-1
Podman version: 84.1-1
OS: Arch Linux

When creating a container and adding and subsequently removing environment variables, the container will not create and will not produce an error.

Steps to reproduce

1. Start container creation
2. Add environment variables
3. Remove said environment variables
4. Click create

An error occurs in the console while validating the variables as they are undefined instead of removed

![image](https://github.com/cockpit-project/cockpit-podman/assets/48085877/1b8b607a-f58b-44b8-9722-3a45163b86db)

![image](https://github.com/cockpit-project/cockpit-podman/assets/48085877/f41a5a91-d77f-4905-80fd-71f1fa33a5b8)

I can't tell whether 85 fixes this, it's not in extra yet

**Comment by jelly** [comment]
Likely 85 won't fix it, I haven't heard of this issue yet.

**Comment by Tiefseetauchner** [comment]
Thx for fixing it
