### ISSUE TITLE
Show memory usage by all images and containers

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#165]
This should help users to see if they need to do some cleanup to free up some space.
This can have similar design as docker (possibly without the free space)
![dockerdesign](https://user-images.githubusercontent.com/12330670/62533355-bb3bf100-b846-11e9-838f-185911cb0860.png)

**Comment by EricJeffrey** [comment]
Now this one. Is there any way to fetch these data? Something related to CGroup? I've taken a look at cockpit-docker, it use `cockpit.metrics` with options like `cpu.usage`. But have no idea how it works at all.

**Comment by marusak** [comment]
> But have no idea how it works at all.

That makes two of us :)

This issue needs some initial investigation. Quickly looking into podman API there is http://docs.podman.io/en/latest/_static/api.html#operation/df  which might provide some useful data. And it surely would be a good idea to understand how this worked in c-docker and if we can get the same/similar data.

Once we know what data we can collect, then we should get some design.

**Comment by EricJeffrey** [comment]
I've got some clue by checking the source code(🤔 a bit tough though). 
- First, the backend clearly support those CGroup stuff, see [cockpitcgroupsamples.c](https://github.com/cockpit-project/cockpit/blob/cf114780928e46c1e4b12ce1a5385fc65ba5f792/src/bridge/cockpitcgroupsamples.c#L29)
- Second, some docker-related prefix of CGroup file path are defined in [client.js](https://github.com/cockpit-project/cockpit/blob/c9341f344623cd6a8759faed97024035943632d5/pkg/docker/client.js#L218)
- Then, using `cockpit.metrics()` together with `cockpit.grid()` to fetch CGroup data from the backend,  [update](https://github.com/cockpit-project/cockpit/blob/c9341f344623cd6a8759faed97024035943632d5/pkg/docker/client.js#L226) data and [handle](https://github.com/cockpit-project/cockpit/blob/c9341f344623cd6a8759faed97024035943632d5/pkg/docker/client.js#L273) them.

I've also tried to fetch these data and it does work:

![image](https://user-images.githubusercontent.com/33823695/88055846-37336400-cb92-11ea-8184-df14cdbef44f.png)
My code here (just a function that log & log & log...):
```js
halo() {
    var cgroup_prefixes = [
        // "init.scope/system.slice/docker-",
        // "system.slice/docker/",
        // "system.slice/docker-",
        // "docker/",
        "machine.slice/libpod-"
    ];
    var usage_samples = [];
    var usage_metrics_channel = cockpit.metrics(1000, {
        source: "internal",
        metrics: [{
            name: "cgroup.memory.usage",
            units: "bytes"
        }]
    });
    usage_metrics_channel.onchanged = function () {
        console.log("onchanged");
        var meta = usage_metrics_channel.meta || {};
        var metrics = meta.metrics || [];
        cgroup_prefixes.forEach(function (prefix) {
            console.log("instance.foreach, prefix: ", prefix);
            metrics.forEach(function (metric) {
                console.log("instance.foreach, metric: ", metric);
                var instances = metric.instances || [];
                instances.forEach(function (cgroup) {
                    console.log("instance.foreach, cgroup: ", cgroup);
                    var id = cgroup.substr(prefix.length, 64);
                    if (!usage_samples[id])
                        usage_samples[id] = usage_grid.add(usage_metrics_channel, ["cgroup.memory.usage", cgroup]);
                });
            });
        });
    };
    
    var usage_grid = cockpit.grid(1000, -1, -0);
    
    usage_metrics_channel.follow();
    usage_grid.walk();
    
    usage_grid.addEventListener("notify", (event, index, count) => {
        console.log("notify, usage_samples: ", usage_samples);
    });
    
    console.log(usage_metrics_channel);
}
```

**Comment by EricJeffrey** [comment]
Could we implement this by using charts lib like `echarts`? I've done some work on this using that. 
If ok or other chart lib, I'll take a try. @marusak (but not `plot.js` in cockpit😅

![image](https://user-images.githubusercontent.com/33823695/88369852-78f72100-cdc3-11ea-8519-cd30ab7c689d.png)

**Comment by marusak** [comment]
Sorry for the late response, this fall through my backlog.

So there are 2 things to consider: memory and cpu usage and disk usage.
I was thinking about disk usage when talking about this card (and thats what is screenshot in the first comment).
However having also memory and cpu usage could be cool as well. I faintly remember there being some discussion what we actually want to show, but I cannot recall what was the conclusion.

@larskarlitski and @martinpitt do you happen to know? Or WDYT, should we show all 3 graphs (2 timelines for cpu and memory and one usage bar for storage) ?

@EricJeffrey what you posted look great though :) We would need to make it fit the page properly, but in general if we want these data, than thats the way to go. About library - I don't have any strong preferences, currently we are talking about what to use to plot graphs in cockpit itself. But if there is library that works well, why not to use it :)

**Comment by EricJeffrey** [comment]
Aha, this what I've done for now:

![image](https://user-images.githubusercontent.com/33823695/88452111-993fe200-ce8e-11ea-8679-66a23f0c051d.png)

Struggled with these data for a while, but looks good now.

**Comment by martinpitt** [comment]
Right, let's please not use plot.js, we are trying to get rid of this. We were experimenting with the PatternFly 4 charts (https://github.com/cockpit-project/cockpit/pull/14353), and with some CSS workarounds they work.

It'd be fine to show the graphs of course, although I'm not sure how well they scale across lots of containers -- we don't want to make the podman start page too heavy. At worst they could go into a subpage? Then you wouldn't incur the extra overhead for everyone, and also wouldn't need to cram them into a small space only.

**Comment by EricJeffrey** [comment]
Alright, at least there is a way to get those data.

**Comment by marusak** [comment]
>  At worst they could go into a subpage? Then you wouldn't incur the extra overhead for everyone, and also wouldn't need to cram them into a small space only.

That seems like the best option as it indeed seems heavy. There is already PR, but moving it to separate page and just linking to it seems like the best option.

**Comment by EricJeffrey** [comment]
Just make a small test on fedora32 and it works fine. Will take a try on this.
