### ISSUE TITLE
Show network related information in container overview

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#168]
Show information like `IP Address`, `IP Prefix Length`, `Gateway`, `MAC Address`...

Keep in mind https://github.com/cockpit-project/cockpit/issues/11470

**Comment by marusak** [comment]
Blocked on https://github.com/containers/libpod/issues/4792

**Comment by EricJeffrey** [comment]
any progress? see [libpod#4792](https://github.com/containers/libpod/issues/4792) closed

**Comment by marusak** [comment]
No progress unfortunately. We are in the middle of migrating to different backend (see https://github.com/cockpit-project/cockpit-podman/pull/352) and then this can be picked up again.

**Comment by EricJeffrey** [comment]
Any work on this? I'd like to do some coding.

**Comment by marusak** [comment]
> Any work on this? I'd like to do some coding.

No, feel free to grab it :)

**Comment by EricJeffrey** [comment]
Need an `inspect` call to get container network infomation? It's not in response of `list containers`.

**Comment by marusak** [comment]
> Need an inspect call to get container network infomation? It's not in response of list containers.

seems like that. Question is, when we should get this info while loading containers, there are 3 options:
1. Load this info right away and resolve (stop showing `Loading...`) only once we have this info for all containers
2. Load this info right away, but don't block on it. Once we get response from inspect calls, then we just update info in the containers list.
3. Load this info only when container details are opened.

While no.3 may seem like the best option (as we would not do bunch of calls and transfer/parse bunch of data) it may seem slow once user opens container details. No.1 seem like the worst option - it would mean that all info would be always available, but the general loading of containers would be slower. So I guess we want to go with no.2 ?

**Comment by EricJeffrey** [comment]
Alright, let's make it clearer :
1. web page will stuck until all inspect is completed and data resolved into component
2. web page won't stuck after `list container`, `inspect` at background, and update when one inspect complete
3. inspect when `∨` is clicked, detail showed
Is that so? This way No.2 surely. What about `create` event, need to do inspect on create too.

**Comment by marusak** [comment]
> Alright, let's make it clearer :

Exactly as you described it.

> What about create event, need to do inspect on create too.

This is handled already. See `handleContainerEvent` in `src/app.jsx`. Of course, if you find out that this mapping is not enough with this `inspect` approach, then things needs to be adjusted to work, as expected.

**Comment by EricJeffrey** [comment]
Ok, another question, what info should be displayed? Below are what we can get from `inspect`:
```
"NetworkSettings": {
    "EndpointID": "",
    "Gateway": "",
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "",
    "Bridge": "",
    "SandboxID": "",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {},
    "SandboxKey": ""
}
```
Maybe just `ip address`, `mac addr`, `gateway`, `ip prefix len`? This is what cockpit-docker shows if I'm right.

**Comment by marusak** [comment]
> Ok, another question, what info should be displayed? ... This is what cockpit-docker shows

Yeah, I would go with that c-docker shows. If we later on decide we want something more/less, it is easy to change.
