### ISSUE TITLE
cockpit.format() strings are incorrectly marked as c-format

### ISSUE THREAD

**Issue by bittin** [cockpit-project/cockpit-podman#1712]
https://translate.fedoraproject.org/translate/cockpit-podman/main/sv/?q=state:%3Ctranslated

this string looks a bit wierd guess the o should not be a part of $0% o

**Comment by goeranu** [comment]
Looking at the code, I believe the string might be intended that way, but it is incorrectly flagged as "c-format". That makes Weblate think something is wrong if something else than an "o" follows the percent sign, which of course is not the case.

**Comment by bittin** [comment]
seems @goeranu have translated this now, but the string is still broken

Back in Fedora business now again after my break

**Comment by martinpitt** [comment]
@bittin Can you please be more specific what you mean? I suppose this is about "$0% of $1 limit" which is completely legit and intended. https://translate.fedoraproject.org/translate/cockpit-podman/main/sv/?q=of+%241+limit&sort_by=-priority%2Cposition&checksum= current Swedish translation is "$0 % av gränsen $1" which looks at least looks plausible.

**Comment by goeranu** [comment]
I don't want to put words in the mouth of @bittin, but let me expand a bit on my comment above in the hope of shedding some light on the confusion.

My understanding is that the `cockpit.format` function will replace $0 and $1 with numbers (a percentage and a limit respectively). That makes total sense.

However, that is not how the string is presented to the translator. When extracting strings, `gettext` (or whatever tool you use), apparently is told the first argument to `cockpit.format` is a format string in the **C language printf()** style. It tags it with `c-format` in the po file. That is, it is interpreted as if the `% o` part was a C format directive, being replaced with an octal number, preceded with a space if positive. It no longer makes sense.

This is aggravated by the fact that Weblate tries to enforce the `c-format` tag. If the translation of the word _of_ does not also start with an _o_, which it doesn't in Swedish, then Weblate signals an error in the translation. I had to explicitly tell Weblate to ignore this error in order for it to accept the translation I made.

Does this make the situation clearer?

**Comment by bittin** [comment]
Found another one in cockpit-files 

any good place to report this one too?

**Comment by jelly** [comment]
> Found another one in cockpit-files
> 
> any good place to report this one too?

Please explain what is wrong with the translation string, @martinpitt and @goeranu have asked / clarified the translation string but you haven't responded. (Just saying it is wrong doesn't help).

**Comment by bittin** [comment]
https://translate.fedoraproject.org/translate/cockpit-files/cockpit-files/sv/?q=has%3Acheck&offset=2 

another broken c-string here and as @goeranu already explained what the problem is, i did not feel i had to explain again and maybe its better to report it here: https://github.com/cockpit-project/cockpit-files 

but as i was busy with both dayjob and washing clothes i did not have time to write a long explanation and as i work for free on my own spare time to try to make your product better i don't feel like arguing
![bild](https://github.com/cockpit-project/cockpit-podman/assets/43197/0fe003ce-843f-4430-9b5d-11fb3dcb740b)

**Comment by martinpitt** [comment]
Thanks @bittin, now I understand. I'll look into that.

**Comment by martinpitt** [comment]
The sad thing is, I [fixed that in cockpit](https://github.com/cockpit-project/cockpit/commit/449d76c0e6d9) 6 years ago, but it never made it into starter-kit and friends. :cry:

**Comment by martinpitt** [comment]
@bittin Fixed in #1763. I fixed c-files in https://github.com/cockpit-project/cockpit-files/pull/586 .

c-machines and c-ostree are not currently affected, but I'll send PRs there as well to avoid this in the future. Thanks for spotting!

**Comment by bittin** [comment]
> @bittin Fixed in #1763. I fixed c-files in [cockpit-project/cockpit-files#586](https://github.com/cockpit-project/cockpit-files/pull/586) .
> 
> c-machines and c-ostree are not currently affected, but I'll send PRs there as well to avoid this in the future. Thanks for spotting!

no problem, and thanks for fixing, closing this issue as fixed :)

**Comment by martinpitt** [comment]
It didn't land yet. It'll be auto-closed, don't worry.

**Comment by bittin** [comment]
> It didn't land yet. It'll be auto-closed, don't worry.

alright sorry did not know that, but then i will let that happen

**Comment by martinpitt** [comment]
The fix landed. I [triggered a new POT export](https://github.com/cockpit-project/cockpit-podman/actions/runs/9657849459) and [weblate correctly shows no c-format any more](https://translate.fedoraproject.org/translate/cockpit-podman/main/sv/?q=of+%241+limit&sort_by=-priority%2Cposition&checksum=).
