### ISSUE TITLE
testHealthcheckSystem pixel flake

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit-podman#1724]
The job `fedora-40/updates-testing` failed on commit 0ec66d38cae6b342712684a251f975e602401e6a.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-0ec66d38-20240523-015503-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Looks like a flake, but low-prio pilot issue

**Comment by jelly** [comment]
I don't see this anymore in our [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=14&repo=cockpit-project%2Fcockpit-podman)? Should we close this?

**Comment by martinpitt** [comment]
Yeah, agreed. Apparently it's rare enough now that we have much bigger worries/flakes.
