### ISSUE TITLE
My system is CentOS Linux release 7.9.2009 (Core). When I installed cockpit-podman and followed the github tutorial make, I reported an error.

### ISSUE THREAD

**Issue by bulibuqiyaoyao133** [cockpit-project/cockpit-podman#1726]
Cockpit version:
Cockpit-podman version:  cockpit-podman-87
Podman version: podman version 1.6.4
OS:
CentOS Linux release 7.9.2009 (Core)

When I use centos7.9, use yum install cockpit and install cockpit-podman, follow the github tutorial to clone to the system directory, open cockpit-podman and make, and I get an error.
![Snipaste_2024-05-24_03-42-46](https://github.com/cockpit-project/cockpit-podman/assets/79575346/efd86ce1-9388-4cc1-9a8d-155f6bddb960)

![Snipaste_2024-05-24_03-41-27](https://github.com/cockpit-project/cockpit-podman/assets/79575346/22fee7a8-e5c5-4fe7-8cef-ea059ea7c51c)

Steps to reproduce

[root@localhost cockpit-podman]# ll
total 72
-rwxr-xr-x 1 root root  3583 May 23 15:02 build.js
-rw-r--r-- 1 root root  3216 May 23 15:02 HACKING.md
-rw-r--r-- 1 root root 26530 May 23 15:02 LICENSE
-rw-r--r-- 1 root root  8720 May 23 15:02 Makefile
drwxr-xr-x 2 root root     6 May 23 15:02 node_modules
-rw-r--r-- 1 root root   466 May 23 15:02 org.cockpit-project.podman.metainfo.xml
-rw-r--r-- 1 root root  1924 May 23 15:02 package.json
drwxr-xr-x 4 root root    62 May 23 15:02 packaging
-rw-r--r-- 1 root root  2162 May 23 15:02 packit.yaml
drwxr-xr-x 2 root root    21 May 23 15:02 plans
drwxr-xr-x 2 root root   191 May 23 15:02 po
-rw-r--r-- 1 root root  1242 May 23 15:02 pyproject.toml
-rw-r--r-- 1 root root  2479 May 23 15:02 README.md
drwxr-xr-x 2 root root  4096 May 23 15:02 src
drwxr-xr-x 4 root root   115 May 23 15:02 test
[root@localhost cockpit-podman]# make
error: unknown option `no-write-fetch-head'
usage: git fetch [<options>] [<repository> [<refspec>...]]
   or: git fetch [<options>] <group>
   or: git fetch --multiple [<options>] [(<repository> | <group>)...]
   or: git fetch --all [<options>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --all                 fetch from all remotes
    -a, --append          append to .git/FETCH_HEAD instead of overwriting
    --upload-pack <path>  path to upload pack on remote end
    -f, --force           force overwrite of local branch
    -m, --multiple        fetch from multiple remotes
    -t, --tags            fetch all tags and associated objects
    -n                    do not fetch all tags (--no-tags)
    -p, --prune           prune remote-tracking branches no longer on remote
    --recurse-submodules[=<on-demand>]
                          control recursive fetching of submodules
    --dry-run             dry run
    -k, --keep            keep downloaded pack
    -u, --update-head-ok  allow updating of HEAD ref
    --progress            force progress reporting
    --depth <depth>       deepen history of shallow clone
    --unshallow           convert to a complete repository

make: *** [pkg/lib/cockpit-po-plugin.js] Error 129

**Comment by martinpitt** [comment]
CentOS 7's `git` version is just too old. This is pretty much a wontfix -- cockpit-podman doesn't work on RHEL/CentOS 7 (as that has no podman), and moreover CentOS 7 is end-of-life. We only support our [development container](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#setting-up-development-container) as dev platform, so you can try your luck with running that through docker -- but that's not supported either (no podman, no toolbox).

So really, please update to some supported OS.
