### ISSUE TITLE
Can not see podman images with rootless user.

### ISSUE THREAD

**Issue by williamjmorenor** [cockpit-project/cockpit-podman#204]
I am not hable to see my user owned images, I have downloaded many images as user as you can se here:

![image](https://user-images.githubusercontent.com/3522386/64998037-db2bef00-d89f-11e9-96ec-f0544a2da14d.png)

But I can not see then with the podman plugin:

![image](https://user-images.githubusercontent.com/3522386/64998107-280fc580-d8a0-11e9-92c4-fb99056fb4ad.png)

Click in "Start podman" not work, refresh the page do not work too.

This happens as normal user, if a login with root there is no problem:

![image](https://user-images.githubusercontent.com/3522386/64998274-b421ed00-d8a0-11e9-8d86-92ca5f4e6c1d.png)

![image](https://user-images.githubusercontent.com/3522386/64998303-d74c9c80-d8a0-11e9-8732-b7885020f877.png)

Since one of the features of podman is to run container as a rootless user should be nice to manage my podman images as normal user.

I am running up to date Fedora Rawhide 

Installed Packages
Name         : podman
Epoch        : 2
Version      : 1.5.2
Release      : 0.89.dev.gita1970e1.fc32
Architecture : x86_64
Size         : 54 M
Source       : podman-1.5.2-0.89.dev.gita1970e1.fc32.src.rpm
Repository   : @System
From repo    : rawhide
Summary      : Manage Pods, Containers and Container Images
URL          : https://podman.io/
License      : ASL 2.0

Installed Packages
Name         : cockpit
Version      : 202.1
Release      : 1.fc32
Architecture : x86_64
Size         : 52 k
Source       : cockpit-202.1-1.fc32.src.rpm
Repository   : @System
From repo    : rawhide
Summary      : Web Console for Linux servers
URL          : https://cockpit-project.org/
License      : LGPLv2+

Installed Packages
Name         : cockpit-podman
Version      : 8
Release      : 1.fc32
Architecture : noarch
Size         : 6.0 M
Source       : cockpit-podman-8-1.fc32.src.rpm
Repository   : @System
From repo    : rawhide
Summary      : Cockpit component for Podman containers
URL          : https://github.com/cockpit-project/cockpit-podman
License      : LGPLv2+
Description  : The Cockpit user interface for Podman containers.

uname -a
Linux Rawhide 5.3.0-0.rc8.git0.1.fc32.x86_64 #1 SMP Tue Sep 10 09:06:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by marusak** [comment]
This is not yet supported.
It is reported in  #83 and in #84.
It is currently work in progress in #173.
