### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [cockpit-project/cockpit-podman#267]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by marusak** [comment]
> - [mandatory] which branch is your development branch?

master

> - [mandatory] have you merged latest translation from Zanata and locked the project?

We have checked 3 days ago and we had the latests updates. I haven't yet locked the project, as first I would like to try interact with weblate and see how it goes and once we know we can do the migration, then I'll lock the project and manually push the newest translations into weblate.

> - [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]

We want to do manual updates. We don't want any automatic PRs with `.po` files updates, nor we will have `.pot` file upstream.

> - [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

LGPL-2.1-or-later

> - [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

Nothing I can think of.

> - [optional] do you need us to activate any specific checks? (this is a setting per component [3])

All the basic ones plus javascript. Also we use `$n` where `n` is number as format string, not sure which rule would match this. But I guess we can tweak these later on.

> - [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No. We will do this manually.

**Comment by marusak** [comment]
Check-list of what we needs to do:

- [ ] Install [weblate client](https://docs.weblate.org/en/weblate-3.9.1/wlc.html) into task container.
- [ ] Teach `po-refresh` bot to dismiss files that have less than 50% translations. This can be read by `msgfmt --statistics <po file>`
- [ ] Get project in weblate (`cockpit`, `martinpitt`, `mmarusak` need to have full access)
- [ ] Rewrite po commands in Makefile to use `wlc`
- [ ] Do successful po-refresh
- [ ] Lock project in zanata, manually sync it into weblate

**Comment by Jibec** [comment]
If you never did it, please connect once to https://translate.stg.fedoraproject.org/ so you exist in the list of users.

**Comment by marusak** [comment]
I have logged into https://translate.stg.fedoraproject.org/ a few days ago already.

**Comment by Jibec** [comment]
Matej, you now have all authorization for the cockpit project in weblate. Please let me know of I can be of any help.
Martin did not connect, I'll add him later.

**Comment by martinpitt** [comment]
I now logged in as myself (`martinpitt`) and as our automation user (`cockpit`), the accounts should exist now. There are several more translators in Zanata, but we can add them back ourselves after the migration. Thanks @Jibec !

**Comment by marusak** [comment]
I added you @martinpitt and also added @cockpituous as admins.

**Comment by Jibec** [comment]
We don't need to provide any specific authorisation for translators. Only for accounts who need to handle project's configuration and or manage translations.

Cockpit user and martin have correct authorization, I assume you did it yourself, which is fine.

I created an empty component for you to do the configuration. Please let me know if I can be of any help.

**Comment by marusak** [comment]
So I tried to update this, but I am struggling to push any changes in any way.
Files I use:
- cs.po: https://github.com/cockpit-project/cockpit-podman/blob/master/po/cs.po
- podman.pot: (just rename to `podman.pot`, github does not allow `.pot` files) [podman.txt](https://github.com/cockpit-project/cockpit-podman/files/4015838/podman.txt)

Here is what I've tried:
1. Using `wlc` to upload to update `cs.po`:
```
 $  wlc --url https://translate.stg.fedoraproject.org/api/ --key <my_api_key> upload -i cs.po cockpit/podman/cs
Error: Failed to upload translations!
```

2. Using `wlc` to upload `podman.pot`:
I did not figure out how to do this. I noticed that you set up `en.po` as source file, but we would rather use `.pot` file. But surely we can use `en.po` if that is the recommended way. (`upload -i podman.pot cockpit/podman/en` fails the same way as previous step.

3. Using git to do changes:
- I cloned this repo as descried in `settings/API access`
- I copied `cs.po` and did `git add` and `git commit`
- `wlc --url https://translate.stg.fedoraproject.org/api/ --key <my_key> push cockpit/podman`
It does not output any error, but `cs.po` in weblate is not updated.

4. Downloading all `.po` files at once with `wlc download`
I can do `wlc --url https://translate.stg.fedoraproject.org/api/  download cockpit/podman/cs`, but I need to download all files at once. Is that possible?

Am I doing something wrongly @Jibec ? Thanks for any help!

**Comment by Jibec** [comment]
If you want Weblate to works, you'll have to commit POT files in your repository.

If you want to limit the number of commits, use both:
* git squash per author or more aggressive squashing https://docs.weblate.org/en/weblate-3.10/admin/addons.html?highlight=squash#squash-git-commits
* let the Weblate Pull request open as long as possible so git squash works on its best.

If you really want any translation commit in your repository, created a dedicated project for po and pot files, and I'll plug Weblate on it.
The file hierarchy I suggest is:

* one "pot" folder containing all pot of the "cockpit-project" organization.
** Example: cockpit.pot, cockpit-podman.pot
* one "po" folder, with one sub-folder per project, in within each project sub-folder: have one file per language.

Controlling Weblate's pushes is easy with automation ([see](https://pagure.io/fork/jibecfed/fedora-websites/blob/weblate/f/alt.fedoraproject.org/pulltranslation.sh)), but not having at all the pot file in the repository isn't a typical usecase for Weblates. Libvirt team did hack the system to make it work, but I don't recommend it and I'm sure they'll have issues in the future.

**Comment by martinpitt** [comment]
Ugh, this really makes stuff ugly.. Maintaining pot files upstream is a nuisance really. We don't want developers to always think of rebuilding and updating it on pull requests, so it would generate a lot of extra commits.

Instead, could we have separate master-weblate, rhel-8.1-weblate etc. branches on our upstream project for this? Our po scripts could then auto-commit/force-push stuff there, regularly pull from these, and all the noise would be limited to the -weblate branches (which nobody would look at).

**Comment by marusak** [comment]
So we decided in https://github.com/cockpit-project/cockpit/issues/13319 that we don't want to do all of this `update .pot file in upstream`, `get PRs from weblate` stuff, and we want to maintain it manually (with bots). Seems it is not possible? **Is there really no other solution that keeping `.pot` file in upstream?** Not even using git somehow to access git in weblate? Also **can you please explain why I cannot use `upload` command?** Seems it should be possible for admins of that project.
As @martinpitt mentioned, in the worst case we could have separate branch (@Jibec talked about separate project (now we would already need 6 projects!)), but we still would get PRs with updates into that branch, right? 

> Controlling Weblate's pushes is easy with automation ([see](https://pagure.io/fork/jibecfed/fedora-websites/blob/weblate/f/alt.fedoraproject.org/pulltranslation.sh))

The script does pulling, not pushing.

**Comment by marusak** [comment]
@Jibec I created https://github.com/cockpit-project/cockpit-podman-weblate repository, which we want to hook up with https://translate.stg.fedoraproject.org/projects/cockpit-podman . Do we need to provide some key, so weblate can directly push into this repository (and not only send PRs)?
Can you also please keep only `master` component?

**Comment by marusak** [comment]
@Jibec I removed all components except `master`. Also switched to our project. Here is problem that it cannot rebase. Can you fix it, or just removing the whole project and creating a new one would be better?

**Comment by Jibec** [comment]
Done.

If you don't want pull requests, I think you have to all this user to commit: https://github.com/weblate

**Comment by marusak** [comment]
https://translate.stg.fedoraproject.org/projects/cockpit-podman/ could the component be called `master` and not `cockpit-podman`?

**Comment by Jibec** [comment]
done https://translate.stg.fedoraproject.org/projects/cockpit-podman/master/

**Comment by marusak** [comment]
Awesome :) I invited https://github.com/weblate into https://github.com/cockpit-project/cockpit-podman-weblate as collaborator. Would that be enough?

**Comment by Jibec** [comment]
yes, and changing the git URL: https://docs.weblate.org/en/weblate-3.10/vcs.html#github-repositories

**Comment by marusak** [comment]
@Jibec So I did translation in https://translate.stg.fedoraproject.org/projects/cockpit-podman/master/sk/ two days ago, but we still did not get commit into https://github.com/cockpit-project/cockpit-podman .
I hope it is just misconfigured and we don't actually need to go into UI and press the `Rebase`, `Pull` or some other button. Can you please take a look?

**Comment by martinpitt** [comment]
@marusak: You mean https://github.com/cockpit-project/cockpit-podman-weblate/ , right?

**Comment by marusak** [comment]
> @marusak: You mean https://github.com/cockpit-project/cockpit-podman-weblate/ , right?

Of course! Sorry for mistake, hope I did not confuse you @Jibec

**Comment by Jibec** [comment]
I can't keep up with one to one exchanges.
Please open your questions on translator mailing list.
The answer is easy, but I want other people to know about it.
