### ISSUE TITLE
Zanata translation locked

### ISSUE THREAD

**Issue by p-bo** [cockpit-project/cockpit-podman#286]
It is not possible to translate, because translation on
https://fedora.zanata.org/iteration/view/cockpit-podman/master?dswid=-1664
is locked.

May I ask you to unlock it please?
Thanks

**Comment by marusak** [comment]
Fedora is migrating from Zanata to Weblate. Cockpit-podman has been already moved.
Please translate in https://translate.stg.fedoraproject.org/projects/cockpit-podman/
