### ISSUE TITLE
autostart for container missing

### ISSUE THREAD

**Issue by S-B-V** [cockpit-project/cockpit-podman#364]
It is a bit annoying that I have to start my containers manually after a reboot of the server, something like auto restart is missing and auto start after reboot of saving of the previous state before the shutdown/reboot.

**Comment by EricJeffrey** [comment]
I think it's clearly said in README:
It is being actively developed and has not yet reached feature parity with cockpit-docker. For now you can do basic image and container tasks for both system and user containers.

**Comment by S-B-V** [comment]
I am aware but I also do not see a roadmap, so I just like to mention it. For sure I am not the only one who is missing it and showing a demand is usually good ;-)

**Comment by marusak** [comment]
We are aware of this and we track it in https://bugzilla.redhat.com/show_bug.cgi?id=1820551
Unfortunately podman itself does not really provide proper way to "autostart" containers either.

**Comment by xer0-1ne** [comment]
A very simple solution is to create a systemd service and enable it for boot.

```
[Unit]
Description=Podman container FOO
Wants=syslog.service
[Service]
Restart=always
ExecStart=/usr/bin/podman start -a FOO
ExecStop=/usr/bin/podman stop -t 10 FOO
[Install]
WantedBy=multi-user.target
```

**Comment by martinpitt** [comment]
That's similar to what `podman generate systemd` does.

**Comment by marusak** [comment]
> A very simple solution is to create a systemd service and enable it for boot.

There is a problem with maintenance of this. We are either going to ignore this and after a while there is going to be a ton of dangling services that don't do anything. We can surely remove associated service when container is deleted using Cockpit, but not when user destroys containers in any other way.

**Comment by web-refinery** [comment]
> > A very simple solution is to create a systemd service and enable it for boot.
> 
> There is a problem with maintenance of this. We are either going to ignore this and after a while there is going to be a ton of dangling services that don't do anything. We can surely remove associated service when container is deleted using Cockpit, but not when user destroys containers in any other way.

A solution may be to create `cockpit-pods.target`<sup>1</sup> and to place service units in `/lib/systemd/system/cockpit-pods.target.wants/`<sup>2</sup>. Then cockpit can occasionally check, for instance via a systemd.timer, which services are dead or have failed and disable them allowing the admin to inspect and correct issues. Disabled service units should probably emit a warning in the webui and be pruned after a set amount of days.

1: man 5 systemd-target
2: Sysadmins can override options in unit files via `systemctl edit`. The overrides are stored in `/etc/systemd/system/` thus leaving the original (cockpit managed) file untouched.
3: I have not tried any of this; and my time to do so is limited. I only puzzled this together by reading the man pages & inspecting my desktop system (i.e. {sound,bluetooth,graphical}.target and such.)

**Comment by marusak** [comment]
> A solution may be to create...

yes, that sounds like a solution, but I think that podman should implement this and not cockpit which is just GUI for podman.

**Comment by jelly** [comment]
Resolved in https://github.com/cockpit-project/cockpit-podman/commit/6966d3959a5f392594e80ac23e7d8b70a2f0d138
