### ISSUE TITLE
Implement omiting hostPort when defining ports

### ISSUE THREAD

**Issue by S-B-V** [cockpit-project/cockpit-podman#365]
If I do not configure the needed ports for the container, there is no random generation of the ports like K8s or docker will do. If I configure no port the container will be isolated which is a bit annoying. If I test something I do not care about the ports and I am not willing to check what is already in use or free and to enter something. It should be done for me, I can later check what port the system  assigned to the container.

**Comment by marusak** [comment]
> If I do not configure the needed ports for the container, there is no random generation of the ports like K8s or docker will do. 

Interesting. So when you do `docker run` it will assign random port?

I am struggling a bit with the idea how do you use a random port? Usually port is a well defined number that some application is communicating through. Can you please explain this a bit more?

**Comment by S-B-V** [comment]
That is how it works currently in my RancherOS environment, here an example, I just configured port 8080, all the other ports where assigned automatically.
This is the command I executed:

`sudo docker run --name openhab_2.5.4 -v /opt/docker_openhab/conf:/openhab/conf -v /opt/docker_openhab/userdata:/openhab/userdata -v /opt/docker_openhab/addons:/openhab/addons -d -e USER_ID=1002 -e GROUP_ID=1002 -e CRYPTO_POLICY=unlimited -p 8084:8080 -p 8443 -p 8101 -p 5007 --restart=always openhab/openhab:latest`

If I do the same and just specify the container ports without adding the host ports it will not generate the random ports, in fact it will ignore it and the container does not has this ports.

![Bildschirmfoto von 2020-04-24 09-33-13](https://user-images.githubusercontent.com/11391862/80191218-afcb6880-8615-11ea-9426-ca57cf203d3c.png)

Here the result if I do the same on my FCOS installation with podman:

`sudo podman run --name openhab_2.5.4 -d -e USER_ID=1002 -e GROUP_ID=1002 -e CRYPTO_POLICY=unlimited -p 8084:8080 -p 8443 -p 8101 -p 5007 --restart=always openhab/openhab:latest`

As a result it creates the ports and expose it with random generated host ports (they are just random generated by creation not at every reboot or restart).

![Bildschirmfoto von 2020-04-24 10-49-23](https://user-images.githubusercontent.com/11391862/80193628-7694f780-8619-11ea-9974-a5ceba859cbb.png)

**Comment by marusak** [comment]
I see, so you just want to be able to only define `containerPort` without `hostPort`, right? Now the UI requires users to define both.

```
--publish, -p=ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort
```

**Comment by S-B-V** [comment]
That is correct as I expect that it behave the same way as the CLI :-)
