### ISSUE TITLE
Web interface issues with some containers

### ISSUE THREAD

**Issue by tgoward** [cockpit-project/cockpit-podman#373]
Running this on a fresh install of fedora 32 server.
The podman container interface is showing many instances of the same root container when only one is running.
![bug](https://user-images.githubusercontent.com/38663379/80895432-2d156e00-8ce5-11ea-8804-71614bfb5bd8.png)

podman ps output :
`# podman ps
CONTAINER ID  IMAGE                                 COMMAND  CREATED         STATUS             PORTS  NAMES
1e317b701907  docker.io/linuxserver/duckdns:latest           45 minutes ago  Up 45 minutes ago         duckdns
3574ec722101  docker.io/library/mariadb:latest      mysqld   2 hours ago     Up 2 hours ago            nextcloudDB

**Comment by marusak** [comment]
Hmm, thank you for the report. Unfortunately I cannot think of any reason for this.
Can you please provide version of podman, cockpit and cockpit-podman?
Also you may try to update to the newest version of all of these 3 components. Is it still reproducible?

**Comment by marusak** [comment]
Closing as not being able to reproduce. Please reopen if still being able to reproduce and then please provide us with more info. Thanks!
