### ISSUE TITLE
CPU and memory usage is static

### ISSUE THREAD

**Issue by EricJeffrey** [cockpit-project/cockpit-podman#376]
`podman top` shows cpu usage 98.309%,  but cockpit-podman show cpu usage 0%, and seems not changing anyway.
![image](https://user-images.githubusercontent.com/33823695/81039609-20a73600-8edc-11ea-9759-cf0df497c75e.png)

![image](https://user-images.githubusercontent.com/33823695/81039656-3c124100-8edc-11ea-8dab-4cc77b600481.png)

**Comment by marusak** [comment]
The problem is that we don't stream this value, just read it once and show that. I have fix ready, but it is now blocked since we are migrating to a new API.

**Comment by EricJeffrey** [comment]
got it

**Comment by marusak** [comment]
Lets keep it open. Good to have a tracker for this.

**Comment by EricJeffrey** [comment]
Now the REST is landed, any plan on this? 
For what I know, the [stats-api](http://docs.podman.io/en/latest/_static/api.html#operation/libpodStatsContainer) is a way to stream resource usage of a container.  Guess it might be better to find way to stream all containers' res usage.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit-podman/blob/master/src/client.js#L69
This place needs to be set up to 'true' and then we need to setup callbacks (similarly like https://github.com/cockpit-project/cockpit-podman/blob/master/src/client.js#L38 is done).
I plan to take a look a bit later on, but if you are interested, please go ahead :)

**Comment by EricJeffrey** [comment]
ok, I'll take a try
