### ISSUE TITLE
Cockpit supporting Debian 8 Jessie

### ISSUE THREAD

**Issue by fraggout23** [cockpit-project/cockpit-podman#383]
I have about 5 servers running debian 8 jessie and ive been wanting to install a server manager but my problem is that cockpit is the only software that seems to support what i require but i guess its targeting unstable machines and i cant install the require files even if i add the backports libgssapi-krb5-2 is the only package that seems to be not working properly.

will cockpit support debian 8 jessie and other previous versions of debian in the future?

please help!

**Comment by martinpitt** [comment]
Sorry, no. Debian 8 has been unsupported for more than two years now. Please don't put any of these machines near the internet.. We don't support this old release for cockpit either.

**Comment by fraggout23** [comment]
Ok thank you, one more question.. Do you guys support only Debian 9 or do you support Debian 10 aswell?

**Comment by martinpitt** [comment]
All Debian ≥ 9 and Ubuntu ≥ 18.04 versions are supported by cockpit. However, I just saw that this is a *cockpit-podman* issue -- currently podman isn't in Debian yet, so neither is cockpit-podman.
