### ISSUE TITLE
rhel 8 beta

### ISSUE THREAD

**Issue by idnovic** [cockpit-project/cockpit-podman#39]
I tried to use it on rhel 8 beta.

I did make, make rpm and installed the rpm.
But it does not work. I have the podman tab and started to podman socket but the ui does not do anything.

Can someone tell me what to do? I can offer log files but I du not know where to look for them for podman cockpit ui

**Comment by rhatdan** [comment]
DId you have the podman-varlink service enabled?
/usr/lib/systemd/system/io.podman.socket
```
systemctl enable io.podman.socket
systemctl start io.podman.socket
```

**Comment by idnovic** [comment]
yes I did. Is the following a problem?
![screenshot 2019-01-15 at 18 41 03](https://user-images.githubusercontent.com/28260793/51198867-bee14800-18f5-11e9-8e77-8451f86876bb.png)

**Comment by idnovic** [comment]
I believe it is because libvarlink-util does not exist in rhel 8 beta.
I installed an version for fedora but I can not connect to the socket.

varlink call unix:/run/podman/io.podman.Ping
Could not Connect

**Comment by rhatdan** [comment]
Is the socket enabled?

**Comment by idnovic** [comment]
yes, works without error msg

**Comment by idnovic** [comment]
can you tell me a simple podman command I can try, maybe a lightweigt container?

**Comment by KKoukiou** [comment]
There is cockpit-podman package in RHEL-8-1 already. Closing this as outdated.
