### ISSUE TITLE
In container bulk-delete mode, rows jumps around

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-podman#40]
When deleting a number of containers, the rows jumps around when others get removed. This can lead to accidentally deleting the wrong container.

**Comment by KKoukiou** [comment]
@andreasn is this still valid? We don't really have bulk deletion in cockpit-podman

**Comment by marusak** [comment]
Indeed. I think this may be closed and another issue created for implementing bulk deletion. There we should think about this problem and design it in a way that it would not suffer with the same problem.
