### ISSUE TITLE
cockpit dashboard should include mapped ports

### ISSUE THREAD

**Issue by joequant** [cockpit-project/cockpit-podman#407]
the cockpit dashboard should include which containers have mapped ports as this is useful diagnostic information.

I can add this to the dashboard if there is a consensus that his is a good idea.

**Comment by marusak** [comment]
Information about ports is available in container/image details.
![ports](https://user-images.githubusercontent.com/12330670/85235355-8e6bda80-b414-11ea-9f10-d686cf461b1b.png)

If I understand this correctly, you would like to see this on the overview to immediately see if the container has some open ports? I don't think we want to show the same information about ports we show in the details on the overview as this line can be rather long.

**Comment by marusak** [comment]
@joequant

**Comment by marusak** [comment]
Closing for lack of information.
