### ISSUE TITLE
Some CSS issues on Epiphany

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-podman#410]
<img width="1440" alt="Screenshot 2020-06-25 at 13 10 04" src="https://user-images.githubusercontent.com/14921356/85709754-db3a0480-b6e5-11ea-9cd4-6a15a99097e0.png">

The Tabs underline is wrong and the Trash Bin icon is wrongly aligned.

**Comment by EricJeffrey** [comment]
The underline seems to because wrong class name `listing-ct-panel`, which should be `ct-listing-panel`, in `lib/listing.scss`  (and some other classnames). 
While the align of TrashBin can be fixed by change `lib/cockpit-components-listing-panel.scss` file:
```
.ct-listing-panel{
    ...
    align-items: center;
}
```

**Comment by marusak** [comment]
Sent https://github.com/cockpit-project/cockpit/pull/14360 to fix this. Once it lands, then we can backport it.
