### ISSUE TITLE
REST not working on Ubuntu

### ISSUE THREAD

**Issue by EricJeffrey** [cockpit-project/cockpit-podman#421]
seems service of podman2.0 in Ubuntu (by kubic) is `io.podman.service,` and `io.podman.socket`, I am wondering that is it enough to only change the `podman.socket` to ``io.podman.socket  in app.jsx ?

**Comment by EricJeffrey** [comment]
also the socket change to `io.podman`

**Comment by martinpitt** [comment]
[Debian](https://tracker.debian.org/pkg/libpod) and [Ubuntu](https://launchpad.net/ubuntu/+source/libpod) still have podman 1.6, thus you need to use an older cockpit-podman release with these. Current master needs podman ≥ 2.0.2 for the REST API.

**Comment by EricJeffrey** [comment]
well, what about package distributed by [kubic project](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/), this is what I'm using, and it's podman 2.0.2.

**Comment by martinpitt** [comment]
@EricJeffrey : For that you need to use current master version of cockpit-podman. There is no release yet, the code just landed last night.

**Comment by EricJeffrey** [comment]
Yeah I'm using current master version, to make it clear:

Podman 2.0 on ubuntu change the listening socket to `io.podman` (looks like so), thus making cockpit-podman cannot work.

Not a big problem though

**Comment by martinpitt** [comment]
The two socket names are not just a rename, they speak completely different protocols. The old io.podman.socket is the varlink API (podman 1.x), podman.socket is the REST API (podman 2.x). I. e. you need matching cockpit-podman and podman versions.

**Comment by martinpitt** [comment]
@EricJeffrey : If kubic really packaged podman 2.0 with an "io.podman.socket" renaming, that's a blatant error and needs to be fixed there.

**Comment by EricJeffrey** [comment]
oh god, I got it. Thanks. my mistake (/(ㄒoㄒ)/~~).

btw, is there any way to change the command of a service? not just the unit file.
