### ISSUE TITLE
General Question  - system // root

### ISSUE THREAD

**Issue by cur1ou5soul** [cockpit-project/cockpit-podman#445]
Dear Cockpit-Podman Comunity, 

I'm just getting started with podman and k8s - I know launched 3 Pods, they show up as 6, 3 Times for root and 3 Times for system.

![image](https://user-images.githubusercontent.com/57013347/87972376-0cc8a480-cac7-11ea-9ace-3763513d5f0f.png)

![image](https://user-images.githubusercontent.com/57013347/87972393-18b46680-cac7-11ea-95ce-4d1caa494649.png)

Could you just give me a hint - 

Thank you

**Comment by marusak** [comment]
I believe you are logged in as `root` into Cockpit, right?
If that is the case, then this is a known bug https://github.com/cockpit-project/cockpit-podman/issues/261 which was fixed this week and will be in cockpit-podman-20, which will get released this Wednesday.

**Comment by cur1ou5soul** [comment]
@marusak Thank you for your kind and fast answer ;-) regards.
