### ISSUE TITLE
Memory limits is incorrectly shown on Ubunut20 when not set

### ISSUE THREAD

**Issue by EricJeffrey** [cockpit-project/cockpit-podman#453]
The Ubuntu20 server in my lab has 64G memory, while in cockpit-podman, the limit in memory field is always 8GiB:

![image](https://user-images.githubusercontent.com/33823695/88368387-8b239000-cdc0-11ea-9a51-f341ee5219c9.png)

And from the stats API of Podman, it's always
```json
{
"memory_stats":{"usage":4284416,"max_usage":9223372036854771712,"limit":9223372036854771712}
}
```
I've done some search, and from [here](https://unix.stackexchange.com/questions/420906/what-is-the-value-for-the-cgroups-limit-in-bytes-if-the-memory-is-not-restricte) it seems this is a way how ubuntu show *no limit*.

I can do some contribution to the code, and I know where to change -->  [utils.jsx](https://github.com/cockpit-project/cockpit-podman/blob/e8c0da2db2029e54e0e61776786b93a50a202507/src/util.js#L17):
```jsx
export function format_memory_and_limit(usage, limit) {
    if (usage === undefined || isNaN(usage))
        return "";

    usage = usage / 1073741824; // 1024^3
    limit = limit / 1073741824;
    var mtext = "";
    var units = 1024;
    var parts;
    if (limit) {
        parts = cockpit.format_bytes(limit, units, true);
        mtext = " / " + parts.join(" ");
        units = parts[1];
    }

    if (usage) {
        parts = cockpit.format_bytes(usage, units, true);
        if (mtext)
            return _(parts[0] + mtext);
        else
            return _(parts.join(" "));
    } else {
        return "";
    }
}
```
but I have no idea how it works and how to change it.

**Comment by marusak** [comment]
Well, the API sends this maximum value, so what cockpit-podman shows is correct.
This should be fixed on podman side to send the correct maximum value. Can you please report this to https://github.com/containers/podman ? Thanks

**Comment by EricJeffrey** [comment]
Ok, but just tell me why we need `usage / 1073741824` ? It's already in bytes(on my ubuntu

**Comment by EricJeffrey** [comment]
From the first time till now, I always believe it's of OS's problem. The limit and usage value may differ from OS, so never mind.

**Comment by marusak** [comment]
> Ok, but just tell me why we need usage / 1073741824

To get to GB.

**Comment by EricJeffrey** [comment]
Wait, won't `cockpit.format_bytes` do that? I mean, give `a=4*1024*1024*1024`, `cockpit.format_bytes(a, 1024, true)` will return `[4,GiB]`. If in this case, why to divide manually?
