### ISSUE TITLE
Ubuntu 20.04 - Service Name is `io.podman.service`

### ISSUE THREAD

**Issue by jkonowitch** [cockpit-project/cockpit-podman#455]
Am hoping to use this on Ubuntu 20.04. There is not apt package, so I placed the v20 release in `.local/share/cockpit/podman`. However, there seems to be a mismatch between what cockpit is expecting (`podman.socket`), and what the service is actually called (`io.podman.socket`).

![image](https://user-images.githubusercontent.com/1221501/88415142-00d13100-cdac-11ea-92ba-de0c0ba4953b.png)

![image](https://user-images.githubusercontent.com/1221501/88414757-5c4eef00-cdab-11ea-914a-9b590cb80d1f.png)

```
$ systemctl --user is-enabled podman.socket
Failed to get unit file state for podman.socket: No such file or directory
$ systemctl --user is-enabled io.podman.socket
enabled

```

```
$ podman version
Version:      2.0.3
API Version:  1
Go Version:   go1.14.2
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by jkonowitch** [comment]
OK so I saw this PR, and I added the `podman.service` per the script. https://github.com/cockpit-project/cockpit-podman/pull/452/files#diff-32136cec674a454aeaac89dbd68bd71dR19-R23

However, I now see this error in the JS console:

![image](https://user-images.githubusercontent.com/1221501/88416214-d1bbbf00-cdad-11ea-9df1-4214158d288a.png)

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit-podman/issues/421
Please look at this issue as it describes yours problem.
