### ISSUE TITLE
Add cockpit-podman to Ubuntu

### ISSUE THREAD

**Issue by durzo** [cockpit-project/cockpit-podman#481]
The blog at https://cockpit-project.org/blog/cockpit-215.html says cockpit-docker has been deprecated in favor of cockpit-podman, but there are no packages available for download for either addon.

Furthermore, https://github.com/cockpit-project/cockpit-podman says that it "has not yet reached feature parity with cockpit-docker".

I can see the 217-2 packages in proposed available at https://launchpad.net/ubuntu/+source/cockpit/217-2 but there is also a lack of docker or podman.

Can you please advise which package we should use, and how to install it on Ubuntu 20.04 LTS ?

**Comment by martinpitt** [comment]
I transfered this to the cockpit-podman project, as it's more appropriate to track here. podman is finally in [Debian](https://tracker.debian.org/pkg/libpod) and the current [Ubuntu development release](https://launchpad.net/ubuntu/+source/libpod), so the biggest blocker got resolved. There is now also Debian packaging files in our upstream, and I just sent an [intent to package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967030) to Debian.

Next steps:
 - [ ] Wait for an updated conmon in Debian: https://bugs.debian.org/cgi-bin/964858
 - [ ] Upload cockpit-podman to Debian, get it through NEW queue
 - [ ] Wait until it hits testing
 - [ ] Get it auto-imported into Ubuntu development release

I'm not sure how well libpod backports, it has quite a lot of build dependencies. So this will most probably not be a 20.04 LTS thing anytime soon, but at least be available in a near release -- it may still happen for 20.10 ("groovy") if all goes well.

**Comment by tborychowski** [comment]
I'm currently on cockpit 215 and Ubuntu 20.04 says it's the latest version. There's also no podman.
Is there any way for me to get it sooner (both the latest version of Cockpit and podman)?

**Comment by martinpitt** [comment]
@tborychowski : Newer cockpit versions are in the [official backports](https://help.ubuntu.com/community/UbuntuBackports), you can just install from there.

podman is only [in the development series right now](https://launchpad.net/ubuntu/+source/libpod), and backporting it will be hard -- it has a ton of build dependencies. Backporting cockpit-podman is easy, but that's not of much use without podman itself. There is an official [PPA from the upstream developers](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa), but it hasn't been updated in a while -- it's still podman 1.6. You can use that with older cockpit-podman versions <= 18.1 if you want.

Sorry, I know that's not a very satisfying answer, but it's really hard to get this into a stable LTS release.

**Comment by tborychowski** [comment]
Hi @martinpitt. 

From the installation docs, I got an impression that it should be available (without backports):
> Cockpit is included in Ubuntu 17.04 and later...

So I enabled backports, and I have the latest version now.
So thanks for that :-)
I'm looking forward to podman!

**Comment by kicsyromy** [comment]
@tborychowski According to the docs on podmain.io there is a repository available[1] for Debian and Ubuntu. I use it personally and works just fine. The only problem I have is that cockpit-podman does not work with this version (says Podman service is not active)
1. https://podman.io/getting-started/installation

**Comment by marusak** [comment]
> The only problem I have is that cockpit-podman does not work with this version (says Podman service is not active)

What version of podman is that?

**Comment by kicsyromy** [comment]
> > The only problem I have is that cockpit-podman does not work with this version (says Podman service is not active)
> 
> What version of podman is that?

Version 2.0.4 is the latest in the repo, and it's the one I have installed.
From what I can tell cockpit-podman is looking for the wrong socket/service names. I have `io.podman.socket/service` and cockpit-podman is looking for `podman.socket/service`

**Comment by marusak** [comment]
> Version 2.0.4 is the latest in the repo, and it's the one I have installed.

Right, that should be fine and is the version we support.

> From what I can tell cockpit-podman is looking for the wrong socket/service names. I have io.podman.socket/service and cockpit-podman is looking for podman.socket/service

There used to be varlink podman API, that was on `io.podman.{socket,service}`. Then they introduced REST API, that is on `podman.{socket,service}`. `cockpit-podman` from version 19 is using this new API.
So if you don't have `podman.{socket,service}` on your system, that is packaging error in ubuntu. There has been some problem with this in debian as well - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966118

**Comment by kicsyromy** [comment]
> > Version 2.0.4 is the latest in the repo, and it's the one I have installed.
> 
> Right, that should be fine and is the version we support.
> 
> > From what I can tell cockpit-podman is looking for the wrong socket/service names. I have io.podman.socket/service and cockpit-podman is looking for podman.socket/service
> 
> There used to be varlink podman API, that was on `io.podman.{socket,service}`. Then they introduced REST API, that is on `podman.{socket,service}`. `cockpit-podman` from version 19 is using this new API.
> So if you don't have `podman.{socket,service}` on your system, that is packaging error in ubuntu. There has been some problem with this in debian as well - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966118

Gotcha! Yeah that makes sense now. Should this be reported to the podman devs? Since the repo is suggested by them as an installation method on Ubuntu.

**Comment by marusak** [comment]
> Should this be reported to the podman devs? Since the repo is suggested by them as an installation method on Ubuntu.

I believe this should be fixed by ubuntu packagers. So issue in Ubuntu tracker would be the best option.

**Comment by madetara** [comment]
I love using both podman and cockpit, and am really looking forward to getting cockpit-podman to Ubuntu 18.04!
Any news on that?

And thanks for the great work

**Comment by martinpitt** [comment]
cockpit-podman finally got into Debian unstable: https://tracker.debian.org/pkg/cockpit-podman :balloon: :tada:

**Comment by martinpitt** [comment]
cockpit-podman is now in the Ubuntu development series: https://launchpad.net/ubuntu/+source/cockpit-podman

[podman itself](https://launchpad.net/ubuntu/+source/libpod) is in Ubuntu 20.10, thus available in the latest stable release. We can backport cockpit-podman there.

**Comment by boistordu** [comment]
So just to clarify(sorry I m a little stupid), there won't be any cockpit-podman for Ubuntu 20.04? Usually I don't like to upgrade server with Ubuntu short releases

**Comment by boistordu** [comment]
And also you mentioned th efact it s lot usable without podman, but podman was supposed to be fully compatible with docker including the name and the symlinks so that there wouldn't be any difference in CLI. So why cockpit-podman isn't using docker then?

**Comment by marusak** [comment]
> cockpit-podman for Ubuntu 20.04

Seems that podman itself is only in 20.10 onward, so not really.

> And also you mentioned th efact it s lot usable without podman, but podman was supposed to be fully compatible with docker including the name and the symlinks so that there wouldn't be any difference in CLI. So why cockpit-podman isn't using docker then?

This one is tricky to answer in short, but lets say "for historical reasons" :)
Longer answer: podman at first introduced varlink API, which was completely different from what docker had. This plugin was created for that API. Then podman decided to create REST API to be compatible with docker. They created legacy mode in this new API for backward compatibility with docker and also a new mode that is providing new endpoints that do not exist in docker. One of them is for example endpoint for pods. So while theoretically we could support also docker API with just some renaming of API path, there are a few inconsistencies that would already need some special cases to hide in docker (like pods, now also container migration...) But honestly, with docker [going on the rouge path](https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/) I don't think we want to spend our effort on it.

**Comment by martinpitt** [comment]
> Seems that podman itself is only in 20.10 onward, so not really.

In the official Ubuntu repository, yes. However, GitHub's action runners use the packages from the OpenSUSE build servers, which work well on 18.04 LTS and 20.04 LTS. See e.g. https://www.vultr.com/docs/how-to-install-and-use-podman-on-ubuntu-20-04 for how to use them.

**Comment by lpj145** [comment]
i try to search lot of sites how to install cockpit-podman on ubuntu 20.10, but i'm not have correct answer so, if you can clarify, is possible to use cockpit-podman on ubuntu 20.10 or not ? i'm trying to install but always i get "Unable to locate package cockpit-podman".

Thanks for attention, congrats great job.

**Comment by martinpitt** [comment]
It was not available in 20.10 indeed. I now created a backport, it should be available on the mirrors in a few hours.
See https://launchpad.net/ubuntu/+source/cockpit-podman for available versions.

**Comment by StevenJonSmith** [comment]
Hey,
Sorry to reply to an old thread, I am a bit of a noob with Linux. I have a headless Ubuntu 20.04 server setup with cockpit and the docker plugin. I want to move to podman, because it's killing me respecing builds for every image update.

I can get podman installed on the server via CLI, but I can't work out how to get the Podman plugin for Cockpit working in my environment. Is this possible, if so a pointer on how would be greatfully appreciated?

**Comment by martinpitt** [comment]
Once you have podman itself installed, you can download the backport for Ubuntu 20.10: https://launchpad.net/ubuntu/+source/cockpit-podman/25-1~ubuntu20.10.1/+build/20407508/+files/cockpit-podman_25-1~ubuntu20.10.1_all.deb

and then install it with `sudo dpkg -i cockpit-podman_25-1~ubuntu20.10.1_all.deb`

**Comment by StevenJonSmith** [comment]
Thank you!
