### ISSUE TITLE
[pod] Create new pod action

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#485]
See https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/podman-pod-groups.png
https://github.com/cockpit-project/cockpit-podman/issues/238#issuecomment-662482073

**Comment by jelly** [comment]
I've looked into creating a pod in c-podman, conceptually it is not that hard but you need to think things through up front:

* The exposed ports from the pod to the outside world (can't be changed afterwards

After the pod is created we can add a new container to the pod. So the easiest would be to extend the current `create container` dialog with an option to select a pod.

Example application / pod usage is running a wordpress container / database in a pod:

  ```
  podman pod create -p 8080:80 -n testpod
  ```

  ```
  podman run \
  -d --restart=always --pod=testpod \
  -e MYSQL_ROOT_PASSWORD="myrootpass" \
  -e MYSQL_DATABASE="wp" \
  -e MYSQL_USER="wordpress" \
  -e MYSQL_PASSWORD="wordpresspass" \
  --name=wordpress-db docker.io/library/mariadb:latest
  ```

  ```
  podman run \
  -d --restart=always --pod=testpod \
  -e WORDPRESS_DB_NAME="wp" \
  -e WORDPRESS_DB_USER="wordpress" \
  -e WORDPRESS_DB_PASSWORD="wordpresspass" \
  -e WORDPRESS_DB_HOST="127.0.0.1" \
  --name wordpress-web docker.io/library/wordpress
  ```

**Comment by renegadext** [comment]
This would be a huge help for us teaching Windows admins how to use Podman out in the field.  Podman and Cockpit are both really awesome in their own right and this feature would a game-changer.

**Comment by jelly** [comment]
Since 5d98049c71791b5a91be0ba2ce9b8877b24ee904 pods can be created in cockpit-podman.
