### ISSUE TITLE
[pod]  Show pod details

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#489]
ID, name, status, created, owner, ports (owner not needed for containers then)

**Comment by stevell3** [comment]
Also add the ability to show the attached volumes.

**Comment by jelly** [comment]
![image](https://user-images.githubusercontent.com/67428/146224670-b0124993-910a-4aa4-8d0e-8e2da91d141b.png)

**Comment by garrett** [comment]
Here's the source
[pod-info.excalidraw.zip](https://github.com/cockpit-project/cockpit-podman/files/7721078/pod-info.excalidraw.zip)

**Comment by jelly** [comment]
This should be implemented in https://github.com/cockpit-project/cockpit-podman/pull/1037
