### ISSUE TITLE
Forced deletion modal can be closed while delete is in progress

### ISSUE THREAD

**Issue by lenticularis39** [cockpit-project/cockpit-podman#504]
The forced deletion modal (`ContainerRemoveErrorModal`) can be closed by the user using the Cancel button while the forced deletion is in progress. This creates counterintuitive behavior, because the operation is actually not cancelled and after clicking the container delete button again, the window reappears, showing the spinner the same as before it was closed.

Moreover when the user opens the modal for a different container while forced deletion is in progress (and the modal has been hidden using the Cancel button), it will display the name of the other container along with the spinner, although it's the first container, not the second one that is the one being deleted.

![2020-08-10-09-17-24](https://user-images.githubusercontent.com/1266171/89759589-ca551f00-daea-11ea-89c4-c97c7e329b85.gif)

**Comment by lenticularis39** [comment]
This probably also affects checkpoint and restore modals, since they are implemented the same way.

**Comment by marusak** [comment]
Right, so this is problem that if the action is still in progress.
I can think of 3 ways how we can solve this:
- Disable the 'Cancel' button if the operation is in progress
- 'Cancel' button would actually "cancel" this operation - which might be tricky, as I don't think you can cancel deletion in the middle.
- 'Cancel' button would not physically cancel the operation, it would just close the dialog and cleanup the state that there is something being removed. It would act more like 'Close'.

**Comment by marusak** [comment]
Well, one more - keep list of containers that are being removed + if they are still in progress.
