### ISSUE TITLE
centos 7

### ISSUE THREAD

**Issue by spacecabbie** [cockpit-project/cockpit-podman#510]
Any way to get this on centos 7 cockpit ?

**Comment by marusak** [comment]
There is currently available `podman-1.6.4-18.el7_8` in centos 7. From master we require `2.0.4`.
We could maybe provide the same thing that we [ship in rhel8](https://github.com/cockpit-project/cockpit-podman/tree/rhel8) but it is rather old and not the most stable thing (problem with the old API).

I don't think that it is worth to ship into centos-7, we should focus on centos-8. But it also does not have yet sufficient version of podman. I can create centos-7 copr for you, but without any liability that it will work (or work well)

**Comment by marusak** [comment]
copr: https://copr.fedorainfracloud.org/coprs/mmarusak/cockpit-podman/

Repo for centos-7 itself: https://copr.fedorainfracloud.org/coprs/mmarusak/cockpit-podman/repo/epel-7/mmarusak-cockpit-podman-epel-7.repo

RPM: https://download.copr.fedorainfracloud.org/results/mmarusak/cockpit-podman/epel-7-x86_64/01614527-cockpit-podman/cockpit-podman-18.1.2.gadd56ed-1.el7.noarch.rpm

Disclaimer - I haven't tested this, so it may or may not work.

**Comment by spacecabbie** [comment]
This so nice thanks for that. Do you want any feedback how it performs ? I understand the focus will be on centos 8 though.

**Comment by marusak** [comment]
> Do you want any feedback how it performs ?

That would be great to know if it is at least usable.

**Comment by spacecabbie** [comment]
> > Do you want any feedback how it performs ?
> 
> That would be great to know if it is at least usable.

Alright i'll log the terminal for you.

**Comment by spacecabbie** [comment]
Well its a bit weird seems to work and all that but get this error:
https://i.imgur.com/0fCKdb6.png
Bit new to containers and podman so googled a bit and downloaded a docker container started it still that error. Unsure if this is my incompetence or a incompatibility.
shell log and output. https://file.io/C1z8G28Gh9UP

**Comment by marusak** [comment]
What is output from `sudo systemctl status io.podman`?

**Comment by spacecabbie** [comment]
> What is output from `sudo systemctl status io.podman`?

I didn't check tbh since it's not supposed to be running. But command line was working.
`[root@vps yum.repos.d]# podman

[root@vps yum.repos.d]# podman pull pihole/pihole:latest
Trying to pull registry.access.redhat.com/pihole/pihole:latest...
  name unknown: Repo not found
Trying to pull registry.fedoraproject.org/pihole/pihole:latest...
  manifest unknown: manifest unknown
Trying to pull registry.centos.org/pihole/pihole:latest...
  manifest unknown: manifest unknown
Trying to pull docker.io/pihole/pihole:latest...
Getting image source signatures
Copying blob 0db2707d1040 [===>----------------------------------] 178.7KiB / 1.8MiB
Copying blob 47b3363e9dca [--------------------------------------] 4.4KiB / 489.4KiB
Copying blob a9232b8f3e23 [======================================] 379.0b / 379.0b
Copying blob 0db2707d1040 [======>-------------------------------] 346.5KiB / 1.8MiB
Copying blob 47b3363e9dca [=>------------------------------------] 27.2KiB / 489.4KiB
Copying blob a9232b8f3e23 done  

Writing manifest to image destination
Storing signatures
4642d275ab7382c208b5ba81f78b672166833fca2f5e3085b93904099f167e47
[root@vps yum.repos.d]# 

[root@vps yum.repos.d]# podman images
REPOSITORY                TAG      IMAGE ID       CREATED      SIZE
docker.io/pihole/pihole   latest   4642d275ab73   8 days ago   303 MB

[root@vps yum.repos.d]# podman run --docker.io/pihole/piholeer.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
Assigning random password: 6Y3O9TEe
  [i] Update local cache of available packages...
  [] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u8

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...
  [] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
chown: cannot access '': No such file or directory
chmod: cannot access '': No such file or directory
chown: cannot access '/etc/pihole/dhcp.leases': No such file or directory
Setting password: 6Y3O9TEe
+ pihole -a -p 6Y3O9TEe 6Y3O9TEe
  [] New password set
Using default DNS servers: 8.8.8.8 & 8.8.4.4
DNSMasq binding to default interface: eth0
Added ENV to php:
"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
"ServerIP" => "0.0.0.0",
"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up: 
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
 ::: Docker start setup complete
  [i] Neutrino emissions detected...

  [] Pulling blocklist source list into range

  [i] Preparing new gravity database...
  [] Preparing new gravity database
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [i] Status: Pending...
  [] Status: Retrieval successful
  [i] Received 58488 domains

  [i] Target: https://mirror1.malwaredomains.com/files/justdomains
  [i] Status: Pending...
  [] Status: Retrieval successful
  [i] Received 26854 domains

  [i] Storing downloaded domains in new gravity database...
  [] Storing downloaded domains in new gravity database
  [i] Building tree...
  [] Building tree
  [i] Swapping databases...
  [] Swapping databases
  [i] Number of gravity domains: 85342 (85298 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [i] Cleaning up stray matter...
  [] Cleaning up stray matter

  [] DNS service is running
  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking

  [] Pi-hole Enabled
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting crond
Starting lighttpd
Starting pihole-FTL (no-daemon) as root
[services.d] done.

Cannot make/remove an entry for the specified session

Cannot make/remove an entry for the specified session
^C
Stopping cron
Stopping lighttpd
Stopping pihole-FTL
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[root@vps yum.repos.d]#`

**Comment by marusak** [comment]
> I didn't check tbh since it's not supposed to be running. But command line was working.

Well, commandline is one thing, cockpit another. We use varlink API that is exposed with this service. If this service cannot start or is failing, then cockpit cannot communicate with podman.
