### ISSUE TITLE
Travis build with arch: PPC64LE 

### ISSUE THREAD

**Issue by ezeeyahoo** [cockpit-project/cockpit-podman#513]
I have trying travis.yml config to succeed. Would you please go through this [build](https://travis-ci.com/github/ezeeyahoo/cockpit-podman/builds/180565507) and let me know if I am going in right direction and warnings are okay?

Thanks

**Comment by marusak** [comment]
I looked at the log and nothing stood up. Can you post warnings that concern you?

**Comment by ezeeyahoo** [comment]
No problem, I got that sorted and raised PR #515. I request you to review.
