### ISSUE TITLE
User tags

### ISSUE THREAD

**Issue by testman42** [cockpit-project/cockpit-podman#520]
I think it would be good idea to allow users to tag containers and container images with custom tags.

Something that would allow for some color-coding in the web interface, so that we have some other option to organise containers and images besides just having a good naming scheme.

Maybe even allow them to have listing of containers / images sorted by tags.

Use case of that is to indicate a group of related containers and images.

For example, Jitsi Meet requires 5 containers.
<img src="https://jitsi.github.io/handbook/docs/assets/docker-jitsi-meet.png" data-canonical-src="https://jitsi.github.io/handbook/docs/assets/docker-jitsi-meet.png" width="80%" height="80%" />

In that case the container name "prosody" doesn't tell me much about what that is, why I have it installed or what it is required for.

But that dilemma would be solved if I could tag the image as "Jitsi".

**Comment by marusak** [comment]
Interesting idea.
There is no such concept in podman itself. That means that Cockpit would have to introduce some of its own configs or some files where such information would be stored - which does not seem ideal.

You can add all of those containers into one pod, then the UI would be clear about it. It would mean that there would be shared network and some other resources between these containers, not sure if wanted or not. (To see how pods are shown you can peak into https://cockpit-project.org/blog/cockpit-225.html)

**Comment by marusak** [comment]
I think that pods would be the way to go.
