### ISSUE TITLE
Podman Service is Not Active (When it is)

### ISSUE THREAD

**Issue by xer0-1ne** [cockpit-project/cockpit-podman#546]
After a recent update, I am now getting an error message that the Podman service isn't running.  I tried downgrading without any luck.  It now seems to be consistent with this error.  The issue is that Podman is running.

## Error message:
<img width="1082" alt="Screen Shot 2020-09-26 at 1 54 50 PM" src="https://user-images.githubusercontent.com/7335096/94347173-13602480-0000-11eb-9cbb-efa0c6b73e1e.png">

## Cockpit status:
<img width="813" alt="Screen Shot 2020-09-26 at 1 56 51 PM" src="https://user-images.githubusercontent.com/7335096/94347205-4aced100-0000-11eb-8730-20591b99612f.png">

## Terminal status or cockpit.service and cockpit.socket:
<img width="1312" alt="Screen Shot 2020-09-26 at 2 00 46 PM" src="https://user-images.githubusercontent.com/7335096/94347284-c29cfb80-0000-11eb-9d77-f86b95992ac0.png">

## cockpit-bridge --packages
<img width="920" alt="Screen Shot 2020-09-26 at 1 57 06 PM" src="https://user-images.githubusercontent.com/7335096/94347211-4efaee80-0000-11eb-8f8a-a7f1bfef0fc4.png">

## installed versions:
<img width="1015" alt="Screen Shot 2020-09-26 at 1 57 58 PM" src="https://user-images.githubusercontent.com/7335096/94347221-5f12ce00-0000-11eb-87c5-37705b5029d7.png">

I am running an Arch Linux machine:
banshee ~ # uname -a
Linux banshee 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux

All other services related to Cockpit seem to be functioning properly.

**Comment by marusak** [comment]
What version of `podman` are you running?

**Comment by xer0-1ne** [comment]
Podman version is 2.1.1-1

**Comment by marusak** [comment]
> Podman version is 2.1.1-1

ok, so my guess was wrong. There was a broken podman version, but this one should be fine. (Possibly the arch version was never patched?)

Do you see anything in your browser logs?

Can you check output of this command? (It should stay listening on events and when you do some action like start a new container it should produce some output and still stay listening)
`sudo curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/libpod/events`

**Comment by xer0-1ne** [comment]
Marusak, 
I downgraded podman back to 2.0.6 and it worked.  
It works for now.  I'll wait for the next update and report back.

**Comment by ardevd** [comment]
I'm having the same issue now on Podman 2.1.1 on Fedora 32. "Podman service is not active" message shows up in Cockpit even though it indeed is active.

**Comment by marusak** [comment]
> I'm having the same issue now on Podman 2.1.1 on Fedora 32.

Can you please provide the following items? Thanks!
- `rpm -q podman`
- `rpm -q cockpit-podman`
- `systemctl --user status podman.service` (run as non-root please)
- `sudo systemctl status podman.service`
- Screenshot of your cockpit podman page (ideally the whole screen)
- Any logs in browser console

**Comment by musiguello** [comment]
I have the same problem with Fedora 33:

- podman-2.1.1-10.fc33.x86_64
- cockpit-podman-24-1.fc33.noarch
- curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/libpod/events
`{"cause":"failed to read message field: bad message","message":"failed to read message field: bad message","response":500}`

**Comment by marusak** [comment]
> curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/libpod/events
{"cause":"failed to read message field: bad message","message":"failed to read message field: bad message","response":500}

This would indeed explain why we say it is not active. This is however unrelated to cockpit. Since I cannot reproduce would you please mind opening issue in https://github.com/containers/podman and linking it then back here? Thanks!

**Comment by musiguello** [comment]
> > curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/libpod/events
> > {"cause":"failed to read message field: bad message","message":"failed to read message field: bad message","response":500}
> 
> This would indeed explain why we say it is not active. This is however unrelated to cockpit. Since I cannot reproduce would you please mind opening issue in https://github.com/containers/podman and linking it then back here? Thanks!

No problem but are you sure this endpoint exists? looking at the REST API reference it seems to always return an error code 500.

https://docs.podman.io/en/latest/_static/api.html#operation/libpodGetEvents

**Comment by marusak** [comment]
> No problem but are you sure this endpoint has not been deprecated? looking at the REST API reference it seems to always return an error code 500.

I see there on the page:

> Responses:
200 returns a string of json data describing an event
500 Internal server error

**Comment by musiguello** [comment]
The origin of my problem was two corrupted files in the journal.

I removed them and now cockpit-podman is working.

**Comment by mplinuxgeek** [comment]
I just wanted to share that corrupted journal entries was also my problem.

podman.service was failing with the below error:
```
Oct 28 20:49:35 nottherealhostname systemd[5424]: podman.service: Failed with result 'protocol'.
Oct 28 20:49:35 nottherealhostname systemd[5424]: podman.service: Unit process 5626 (podman pause) remains running after unit stopped.
Oct 28 20:49:35 nottherealhostname systemd[5424]: Failed to start Podman API Service.
```
Running `sudo journalctl --verify` showed that there were corrupted journal files so the fix was:

```
sudo journalctl --vacuum-time=7d
sudo journalctl --verify
```

After the above 2 commands podman.service started without issue.

**Comment by marusak** [comment]
This does not seems to be cockpit-podman specific. Partly maybe podman specific as it cannot start when journal is corrupted.
