### ISSUE TITLE
Container search: Improve performance

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#55]
I figured out podman searching and timing issues a bit:

You can specify the source to search by doing site/string:

Here's an example for searching ruby packages:

```bash
# Searching everything

$ time podman search ruby | wc -l     
65
podman search ruby  0.26s user 0.08s system 2% cpu 13.778 total


# Individual searches

$ time podman search docker.io/ruby | wc -l                 
25
podman search docker.io/ruby  0.14s user 0.03s system 10% cpu 1.623 total

$ time podman search registry.fedoraproject.org/ruby | wc -l
1
podman search registry.fedoraproject.org/ruby  0.08s user 0.02s system 5% cpu 1.867 total

$ time podman search quay.io/ruby | wc -l  
25
podman search quay.io/ruby  0.08s user 0.02s system 3% cpu 2.605 total

$ time podman search registry.access.redhat.com/ruby | wc -l
11
podman search registry.access.redhat.com/ruby  0.08s user 0.02s system 6% cpu 1.697 total

$ time podman search registry.centos.org/ruby | wc -l
3
podman search registry.centos.org/ruby  0.10s user 0.03s system 3% cpu 3.383 total
```

The line with numbers is the number of results per repo. For the time value, check the total for the round-trip time.

Adding all the individual totals gives me 11.175 seconds, which is still less than the 13.778 seconds than the total — but it is in the same ballpark.

Parallelizing it ourselves would cut down search results from 14 seconds total to the slowest result, which in this case is 4 seconds (CentOS is the slowest, followed by Quay) here... and we could then have a progress bar instead of a spinner (based on # of results), and that should _also_ help things feel faster too. (Of course, people with better networks would have better results than I get too.)

Ideally, Podman itself would run the searches in tandem, but at least we should be able to work around it.

**Comment by garrett** [comment]
These sources come from `/etc/containers/registries.conf`. Here's a snippet:

```toml
[registries.search]
registries = ['docker.io', 'registry.fedoraproject.org', 'quay.io', 'registry.access.redhat.com', 'registry.centos.org']
```

**Comment by garrett** [comment]
Make sure to return the results in a cache keyed on a the stripped query string so we won't have a race condition with results. Then merge the results together.

(Even with the slow, merged results, it would be possible to have a race condition as we're possibly starting multiple searches based on typing speed.)

I suggest using a cache here instead of `.abort()` as I guess we're not using XHR, but querying Podman's API which might not have an abort function. Also, by caching it, we can have instant results on a repeat string (when someone backspaces or searching for the same string, if they're adding multiple, related containers).

**Comment by larskarlitski** [comment]
Thanks for investigating this!

It's currently not possible to only search specific registries in podman's varlink API. I agree with your assessment that search should be parallel, but I'd like to see that work in podman. This way users of the command line benefit as well.

I've filed https://github.com/containers/libpod/issues/2345

**Comment by garrett** [comment]
When podman implements searching in parallel (and filtering too), would it be able to also report back status via the API, so we could have a progress bar (which would feel faster than a spinner)?

**Comment by larskarlitski** [comment]
> When podman implements searching in parallel (and filtering too), would it be able to also report back status via the API, so we could have a progress bar (which would feel faster than a spinner)?

I'll work with them that it does. We could even show results as they're coming in, no?

**Comment by garrett** [comment]
We possibly could show results as they stream in. My concern with that, however, is that someone will want to try interacting with the results and then everything shifts around, causing frustrating misclicks.

**Comment by marusak** [comment]
Parallel search in podman now exists.
Now:
```
time podman search ruby | wc -l 
74

real	0m1.568s
```
and just one registry:
```
time podman search quay.io/ruby | wc -l 
26

real	0m1.452s
```

So it does not make sense for us to call it for every registry separately. It would only complicate things.
The only remaining thing is that podman could provide status, so we could show progress bar.
I am not absolutely convinced that we need this. The search seems very fast and in majority of cases it would show 0% and then jump to the end. (When I run just search it takes approximately the same time as querying any single registry). It would be useful if there would be one or two very slow registries, but I think in majority of cases spinner is more useful.

**Comment by garrett** [comment]
Nice. Works for me!
