### ISSUE TITLE
Container search: Empty state

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#56]
The container search should have an empty state. I'm not sure what it should be, but a couple of ideas come to mind:

1. Previous successful searches (that either had a click in the list or a container was added?)
2. Previously used containers
3. Popular containers?
4. Show which registries will be searched?

Using previous items would mean there's still an initial empty state that's not useful. Also, it would imply we're storing something somewhere. I guess we'd have to use browser storage or cookies or something and then it's specific to that browser and host that Cockpit is running on.

Popular containers would require querying. And it probably will be irrelevant to most people too.

Showing which registries would be searched might be useful? And then there could be a link to the registries editor to add/remove/disable/enable?

I'm currently leaning to a few previous successful searches at the top with the registries that will be searched below it.

But really, I'm unsure of what would be best, or what else we might have there. Does anyone else have ideas?

**Comment by marusak** [comment]
> Previous successful searches (that either had a click in the list or a container was added?)

This could be possibly useful. But as you mentioned we still would need empty state before you did the first search. And also, we would need to store this somewhere (in browser).

> Previously used containers

I am not sure what this means.

> Popular containers?

I don't this this is any useful.

> Show which registries will be searched?

This actually would be very useful. And also with possibility to manage registries (see https://github.com/cockpit-project/cockpit-podman/issues/85) it would be double useful.

> I'm currently leaning to a few previous successful searches at the top with the registries that will be searched below it.

Sounds like a good idea. Could we get some design for this?

**Comment by marusak** [comment]
We now have list of registries so showing them again does not bring any useful info. Maybe we could then show last few succesful searches but that is bit meh anyway. 

Now it looks like this:
![currentsearch](https://user-images.githubusercontent.com/12330670/100436761-14fda580-30a0-11eb-9c26-b8996b116ef5.png)

So I think we can just put there 'Type to find images' kind of message to show there are no results. Also we can just use empty-state component to make it look the same when the search is in progress and when there are no found results. Currently it looks always differently.
