### ISSUE TITLE
cockpit podman does not show different tags for same image

### ISSUE THREAD

**Issue by daniel-wtd** [cockpit-project/cockpit-podman#563]
Hi all,

I am using coclkpit-podman and cockpit. Unfortunately, it seems, that images with different tags are not properly displayed.

Reproduce:

1. Running fedora 33
2. install cockpit 229
3. install podman 2.1.1
4. run `podman pull mariadb:10` and `podman pull mariadb:latest`
5. Check the cockpit-podman page -> only latest is shown

Would be awesome, to get some ideas / support here :) Maybe I am just doing something wrong.

Best regards,
Daniel

**Comment by marusak** [comment]
![latest](https://user-images.githubusercontent.com/12330670/96331787-732a7800-1060-11eb-8241-6d7443dd305b.png)
It is shown under `Tags` as they both are the same image.
Does it work for you?

**Comment by daniel-wtd** [comment]
Indeed, this works.

It's somewhat un-intuitive, but thats maybe only me.

Thanks a lot.

**Comment by marusak** [comment]
> It's somewhat un-intuitive, but thats maybe only me.

We have discussed this in the team before and there is no ideal case really. We can either show all tags separately but that may pollute the UI unnecessary. Also it makes it so much more work to delete an image that has a few tags, as you need to click on every tag, click on delete, confirm and repeat. Now it is done in one go (we support also untagging).
