### ISSUE TITLE
Containers & images listed twice, owned by root and by system, when logged in to Cockpit as root.

### ISSUE THREAD

**Issue by ledlamp** [cockpit-project/cockpit-podman#565]
Surprisingly didn't find this issue already opened. I use Cockpit as root and as you can see, all podman images and containers are listed twice. 

![image](https://g3jg.qonq.gq)

**Comment by marusak** [comment]
> Surprisingly didn't find this issue already opened.

It is already closed :) https://github.com/cockpit-project/cockpit-podman/issues/261

What version are you on? It was fixed in version 20

**Comment by ledlamp** [comment]
> > Surprisingly didn't find this issue already opened.
> 
> It is already closed :) #261
> 
> What version are you on? It was fixed in version 20

Oh. I have version... 211.3 😕
on CentOS 8, all packages up to date.
I wonder how long until I get the fixed version.
Oh well, that issue doesn't have any keywords I thought of searching, so now more people can find the issue with different keywords 🙂

**Comment by marusak** [comment]
> Oh. I have version... 211.3

version of `cockpit-podman` not of `cockpit`.
