### ISSUE TITLE
issue pulling containers under podman

### ISSUE THREAD

**Issue by badbyt3** [cockpit-project/cockpit-podman#595]
Cockpit version: 230
OS: manjaro (archlinux derivative)

Upon downloading/pulling any container in the 'Podman containers' section, I get the following message:

```
Failed to download image docker.io/astroautomation/statsd-graphite-graphana:latest
Error message:Unexpected token { in JSON at position 84
```

A moment later I see the desired container listed in the Images section, and you can run them normally.
And after a while the podman process hugs one core to 100% causing the fan to ramp up although I have no containers running.

Steps to reproduce:
1. In the podman containers section, click on 'Get new image'
2. Enter in the searchbox any name you want in my case it was graphana

![chrome_TRgR0kk4yu](https://user-images.githubusercontent.com/1003490/98800787-2a709f80-2411-11eb-9f79-1f6538f95dc8.png)

**Comment by allisonkarlitskaya** [comment]
cockpit nor cockpit-podman contain any mention of docker.io/astroautomation/statsd-graphite-graphana:latest.  There seems to be a problem with your local configuration.

Did you try to do something with the above container at some point already?  Do you know where this image name came from?

**Comment by marusak** [comment]
I can reproduce with any image. I just need to search for anything.
The problem is that when we call API it first returns some partial answer that we fail to parse and only later it returns full answer.
