### ISSUE TITLE
Invalid date for all images

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#599]
Oddly, all my images have an invalid creation date.

Is this from podman? Is it the podman API? Is it our code? Is it from Moment? :shrug: 

![Screenshot_2020-11-17 Podman Containers - garrett Rain](https://user-images.githubusercontent.com/10246/99410058-5220a580-28f2-11eb-94ad-c9dca56deffa.png)

**Comment by garrett** [comment]
Podman at the command line shows a date:

```sh
$ podman images
REPOSITORY                                     TAG     IMAGE ID      CREATED        SIZE
registry.fedoraproject.org/f32/fedora-toolbox  32      5e53ba977cfe  2 months ago   345 MB
registry.fedoraproject.org/f33/fedora-toolbox  33      95dc9d4b0f27  2 months ago   327 MB
registry.fedoraproject.org/f29/fedora-toolbox  29      4a6adf1f2a96  12 months ago  438 MB

$ podman --version
podman version 2.1.1
```

**Comment by garrett** [comment]
Dates are working on master, but they're mm/dd/yyyy instead of relative dates and they're misaligned (as they should be right aligned).

![Screenshot_2020-11-17 Podman containers - garrett Rain](https://user-images.githubusercontent.com/10246/99414447-1c31f000-28f7-11eb-8412-44eefa2f6f94.png)

Closing though, as they exist.

**Comment by marusak** [comment]
This was fixed month or so ago. Very likely you don't have the newest c-podman installed.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit-podman/commit/396781b3d7a23f276e4188dcf48123c1daf200c4

Fixed in version 22

**Comment by garrett** [comment]
I was on the badges branch. For whatever reason, git didn't update it to the latest. When I checked master, I saw it was fixed and closed it with a comment. :wink:
