### ISSUE TITLE
Add missing tests

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-podman#6]
This was some leftover from PR #3, but this got landed with incomplete tests to not further drag it out. At least these tests are missing:

- [x]  Start a running container and make sure that it appears so.
 - [x] Check that container names and container commands are shown correctly. Particularly with commands that have more than one word, to cover correct spacing.
- [x] Cover the "Commit", "Delete", and "Start" buttons in container details. The latter currently causes a crash, this needs to be fixed as well.
- [x] Image details and deletion.

**Comment by martinpitt** [comment]
@QiWang19

**Comment by marusak** [comment]
I believe all of these are currently tested.
