### ISSUE TITLE
Validate fields in run image dialog

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#609]
When user for example does not specify container port or just one path of volumes, we silently ignore these. Also we use `parseInt`  to convert fields into numbers which may not behave as we expect (as it silently ignores invalid strings).

We should show which fields are required and are not filled and which should contain number but don't. We may also do additional checks like check if IP is valid etc.

Most of these check should be done on submitting the dialog. We may want to try to show it dynamically, but we need to be careful not to show 'This field is required' error before user had chance to get to this field.

**Comment by jelly** [comment]
We should also check if the container name does not already exists with `http://podman.io/libpod/containers/{name}/exists`

**Comment by garrett** [comment]
All of these checks are good ideas.

Be careful with the port check. It might be different when you have a container inside of a pod.

**Comment by martinpitt** [comment]
@jelly: My gut feeling is that trying to predict host port collisions is over the line. It's really difficult to do, as you may have some ports which are only open on a subset of network interfaces. It's also racy -- some other service or container might start in the meantime and make it fail anyway.

Silently ignoring values is obviously bad, but port/name collisions will have a clear failure mode on creation, which we need to show in the dialog. Then the user can adjust values, and try again.

What do we gain from such overly involved/aggressive LBYL checks?

**Comment by garrett** [comment]
> What do we gain from such overly involved/aggressive LBYL checks?

Preventing users from trying to create something again and again with errors each time, especially after context switches.

https://www.nngroup.com/articles/errors-forms-design-guidelines/

However, point 7 is also important: "Don’t Validate Fields Before Input is Complete"

Here's PatternFly's guidelines on error validation:

https://www.patternfly.org/v4/components/form/design-guidelines/#errors-and-validation

It has guidelines on when to use inline validation:

> Validation on loss of focus occurs as soon as a field loses focus. It alerts users of errors immediately after they complete their input through inline validation, allowing them to quickly see and address issues.
> 
> Validate errors on loss of focus when:
> 
> - A user enters data in an invalid format.
> - A user leaves a required field blank.
> - A user leaves a required field incomplete.

It isn't a choice between inline and on submit error checking; both should be done to some degree.
