### ISSUE TITLE
JSON Error on Arch

### ISSUE THREAD

**Issue by sempervictus** [cockpit-project/cockpit-podman#640]
When attempting to install an image from the Cockpit UI, this error message is thrown instead of deploying the image:
```
Danger alert:Failed to download image docker.io/bytemark/smtp:latest
Error message:Unexpected token { in JSON at position 64
```

**Comment by michael-c-hoffman** [comment]
I too am receiving this error:
cockpit-podman-26-1.module_el8.4.0+581+8bd31022.noarch
The image does infact download and am able to start and run a container using the downloaded image correctly, this seems to be more of a cosmetic issue than an actual error.

**Comment by marusak** [comment]
Good catch, thanks! I sent https://github.com/cockpit-project/cockpit-podman/pull/642 which fixes this.
