### ISSUE TITLE
Unable to set SELinux Label

### ISSUE THREAD

**Issue by loudambiance** [cockpit-project/cockpit-podman#659]
On Fedora v33, with Podman v2.2.1 (installed from Fedora repo), When I create a container from an image and attempt to add a Volume, I can not change it from "No SELinux label" to "Shared" or "Private".

I can not find any log entries indicating an error has occurred in journalctl when watching the podman or cockpit units. The dropdown simply refuses to change. 

I was receive the same behaviour in Chrome, Firefox, and Edge (chromium based version).

**Comment by loudambiance** [comment]
Additional details I was able to sus out. In DevTools in Chrome, I was able to find on the Podman page of Cockpit, I am seeing the following errors:

> GET https://192.168.1.3:9090/cockpit/$-redacted-/podman/po.js net::ERR_ABORTED 404 (Not Found)

The redacted portion matched the ETAG from the response header, not sure if this is sensitive or not.

> FormSelect.js:15 FormSelect requires either an id or aria-label to be specified
> FormSelect @ FormSelect.js:15
> ga @ react-dom.production.min.js:134
> Rs @ react-dom.production.min.js:176
> _o @ react-dom.production.min.js:263
> cl @ react-dom.production.min.js:246
> ol @ react-dom.production.min.js:246
> Qo @ react-dom.production.min.js:239
> (anonymous) @ react-dom.production.min.js:123
> t.unstable_runWithPriority @ scheduler.production.min.js:19
> Bi @ react-dom.production.min.js:122
> Vi @ react-dom.production.min.js:123
> qi @ react-dom.production.min.js:122
> A @ react-dom.production.min.js:287
> Jt @ react-dom.production.min.js:68

**Comment by marusak** [comment]
> I can not change it from "No SELinux label" to "Shared" or "Private".

oh good catch, thanks! Actually if you select something from select, it will be applied, just the UI is not updated correctly. I am sending fix now.
