### ISSUE TITLE
cockpit-podman rpm in fedora 

### ISSUE THREAD

**Issue by dustymabe** [cockpit-project/cockpit-podman#67]
There is a cockpit-docker subpackage in fedora but I don't see a cockpit-podman subpackage. Is this planned?
https://apps.fedoraproject.org/packages/cockpit/

**Comment by marusak** [comment]
Yes, it is planes soon-ish. We did preview release of cockpit-podman a week ago in copr.
https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-podman/

**Comment by marusak** [comment]
A `cockpit-podman` package has been introduced to fedora, see
https://bodhi.fedoraproject.org/updates/FEDORA-2019-43059d2775
