### ISSUE TITLE
WebUI shows: Podman Service is not active

### ISSUE THREAD

**Issue by cmonty14** [cockpit-project/cockpit-podman#693]
Hello,
I have installed packages
cockpit
cockpit-podman
from Debian testing.

When I login to cockpit and select "Podman-Container" I get this message:
Podman Service is not active
![2021-03-14_10-53](https://user-images.githubusercontent.com/12523591/111064401-25515900-84b4-11eb-803a-3f11c120db68.png)

Please advise how to fix this issue.

THX

**Comment by martinpitt** [comment]
It already tells you how to fix it -- click on "Podman starten" to activate the podman service. It will also be started by default from then on -- if you don't want that, uncheck the checkbox.

**Comment by cmonty14** [comment]
Well, unfortunately it's not that simple.
Certainly I clicked on "Podman starten", but nothing happens.

**Comment by martinpitt** [comment]
What is the output of `systemctl status podman.service`? It seems podman crashes for you then.

**Comment by cmonty14** [comment]
```
root@pc4-pve:~
$ systemctl status podman.service
● podman.service - Podman API Service
   Loaded: loaded (/lib/systemd/system/podman.service; static; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:podman-system-service(1)
```

**Comment by martinpitt** [comment]
What happens if you do 

    sudo systemctl start podman.service

? What does "status" say after that?

**Comment by cmonty14** [comment]
```
locadmin@pc4-pve:~$ sudo systemctl status podman.service
● podman.service - Podman API Service
   Loaded: loaded (/lib/systemd/system/podman.service; static; vendor preset: enabled)                                                                                   
   Active: inactive (dead)
     Docs: man:podman-system-service(1)
locadmin@pc4-pve:~$ sudo systemctl start podman.service                                                                                                                  
Failed to start podman.service: Unit podman.socket is masked.
locadmin@pc4-pve:~$
```

I think there's an issue with the podman systemd files.

**Comment by martinpitt** [comment]
"Unit podman.socket is masked." ugh, yes -- try `systemctl unmask podman.socket`.

**Comment by marusak** [comment]
Not related to cockpit, so closing.

Of course, it is questionable why it was masked by default but that is maybe something distro specific?
