### ISSUE TITLE
image and container list loading forever

### ISSUE THREAD

**Issue by jmaris** [cockpit-project/cockpit-podman#708]
Hi,

I've just set up podman on my manjaro-based NAS. When I go to cockpit, however, the list of images and containers never loads.

JS Console gives me the error:
`
Failed to do Update Images: {"status":500,"reason":"Internal Server Error","message":"Failed transform image summaries: failed to obtain summary for image 8c329438a7500afb8879d88ec1273030d0986ab076dce0de9f53d132d09b4784: stat /var/lib/containers/storage/overlay2/425161e64dc0adac0950375271f0a094f3ba638de6c364e9527775d1ca6d966d: no such file or directory","problem":null,"cause":"stat /var/lib/containers/storage/overlay2/425161e64dc0adac0950375271f0a094f3ba638de6c364e9527775d1ca6d966d: no such file or directory","response":500}`

I'm not sure if this is a podman related error or a cockpit one.

Any help is much appreciated, if you need any further files from me please do not hesitate;

**Comment by marusak** [comment]
We are not testing manjaro nor I have access to any such machine so I'll need your help to debug this.

> the list of images and containers never loads.

Is it stuck on spinner with `Loading` or in what state the page stays?

> JS Console gives me the error:

I believe this one should not case page not to load.

A few questions to start with:
- What is your cockpit version?
- What is your cockpit-podman version?
- What is your podman version?

**Comment by jmaris** [comment]
Hey,
Sorry for the late reply, I found it to be some podman containers that had been deleted but that were still being referenced. So this is not an issue with cockpit.
