### ISSUE TITLE
User Podman Service Not Starting - Console Shows Error Message

### ISSUE THREAD

**Issue by iUnknwn** [cockpit-project/cockpit-podman#725]
Cockpit version: 244.1
OS: Centos Stream
Page: Podman

When user/rootless podman containers are running, the interface shows an alert that you can start the user podman service:
![image](https://user-images.githubusercontent.com/1129122/120943980-08a97380-c6e7-11eb-8847-b3328f157ed2.png)

However, clicking the "Start" button does nothing (the alert remains visible and user containers do not appear). Additionally, a message in the console is generated:

```
{
    "problem": null,
    "name": "org.freedesktop.DBus.Error.UnknownInterface",
    "message": "Unknown interface 'org.freedesktop.systemd1.Service'."
}
```

The console shows it comes from `overview.js:336`

As far as I can tell, podman rootless containers are running as expected on the system, and are working normally.

**Comment by martinpitt** [comment]
What does `systemctl --user status` show as that user? Looks like the user systemd instance isn't even running?

**Comment by iUnknwn** [comment]
So this is interesting. 

After a reboot, Cockpit-Podman was working fine, the button worked, no issues.

The system has now been online for about 24 hours, and, while the services in user podman are still working (the containers are still running), `systemctl --user status` shows 2 failed units:

  - podman.service
  - podman.socket

The button is now not working again.

Looking at the logs, I'm seeing several 'too many open files' errors for podman.service, and 'trigger limit hit' errors for podman.socket. 

This looks like this is a podman issue. I'll open a bug there. 

As a feature request, it would be nice if there was some sort of error message though in Cockpit-Podman, since the button, since there's no feedback if the button fails.
