### ISSUE TITLE
How to add additional parameters via the UI? 

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [cockpit-project/cockpit-podman#728]
for example : https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/ 

like: 
```
   hostname: mail
    domainname: example.org
    container_name: mail
```

**Comment by marusak** [comment]
We don't support "adding additional parameters" and I think we don't plan on doing so.
Setting hostname (as with `podman run --hostname=mail`) could be implemented, but currently is not. Do you have some specific requirements that you would need from the UI to support?
