### ISSUE TITLE
CPU value spikes quite a bit, is not rounded, and display in list jumps around

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#740]
I'm running Cockpit 247 with Cockpit-Podman 32 on my home server.

I have a few containers for various services, including a Minecraft (Java) server for my nephews. Most containers are well behaved, but the Minecraft one spikes the CPU, especially after a reboot for quite some time as it sets everything up.

As a result, the CPU for the Minecraft server container runs high and fluctuates a bit.

It doesn't look so great in Cockpit-Podman however. Here's a video I took using Kooha:

https://user-images.githubusercontent.com/10246/126754174-a9656713-ec7a-43b8-aafe-a878cb2f51f6.mp4

Three problems:

1. It's reporting absurd CPU percentages during a spike
2. The CPU reporting isn't rounded
3. The elements in the table shift around (due to the quickly changing, non-rounded CPU spikes; this is more of an effect of 1 and 2)

**Comment by marusak** [comment]
> 2. The CPU reporting isn't rounded

It is, to two decimal places.

> It's reporting absurd CPU percentages during a spike

Hmm, I guess it comes from podman directly? Can you check with `podman stats` if it reports the same values?

**Comment by jelly** [comment]
I can reproduce the issue after restarting a container, I am not certain if it's an API issue or somewhere in the cockpit bridge?

Sometimes the websocket has a very unusual value
![image](https://user-images.githubusercontent.com/67428/132352003-977244f5-3b84-47f4-a22e-b9daf6207937.png)

I have not managed to reproduce this by viewing the stats of the same container with a direct curl of the rest API
```curl -s  --no-buffer --unix-socket /var/run/podman/podman.sock http://localhost/v1.12/libpod/containers/1246dee732ba/stats | jq '.cpu_stats'```

**Comment by jelly** [comment]
Reported upstream https://github.com/containers/podman/issues/11469

**Comment by martinpitt** [comment]
Thanks @jelly! Closing in favor of the podman issue.
