### ISSUE TITLE
"Search for an image" dialog does not show "Owner" radio toggle when access changes

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-podman#772]
When a logged in administrator switches from administrative access to limit and back the "owner" option in the "Download new images" dialog is not shown anymore.

**Comment by abhijeet-26** [comment]
Could you provide more details?

**Comment by KKoukiou** [comment]
@abhijeet-26 the https://github.com/cockpit-project/cockpit-podman/issues/772#issue-1005402142 is quite detailed. Did you try to run cockpit -> go to the podman page -> find the mentioned dialog?

**Comment by jelly** [comment]
Here is a quick video, showing that switching back and forth from administrator access no longer shows the "owner" option:
[Screencast from 2023-03-01 13-29-02.webm](https://user-images.githubusercontent.com/67428/222140079-d7b3f2b5-2e8f-49d2-9f05-eee93668d6b3.webm)

**Comment by jelly** [comment]
Turns out that this is no bug, the system service isn't started as seen in the video and then the owner option would not be shown. So this is fully as expected but maybe not super obvious.
