### ISSUE TITLE
Show privileged containers as non-root user

### ISSUE THREAD

**Issue by tonyjames** [cockpit-project/cockpit-podman#80]
Per this link [1], there are some limits to rootless podman.  It would be useful to have the option to show/manage privileged containers (aka root user's) as a non-root user.  Cockpit already has the option, at login, to re-use the password for privileged tasks.

[1] https://github.com/containers/libpod/blob/master/rootless.md

**Comment by KKoukiou** [comment]
@tonyjames I think what you ask is already implemented since the start of this plugin. You will see root's containers and images if you connect to cockpit as a normal user and allow privilege escalation. (Of course the user needs to have admin priviledges)

**Comment by marusak** [comment]
As @KKoukiou wrote, this is implemented. Yet we don't support showing non-root containers.
