### ISSUE TITLE
commit image dialog needs UI attention

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#818]
![141472940-e3e8db06-c815-424d-b7c5-72f8663bef9c](https://user-images.githubusercontent.com/10246/141748457-582805e9-4f0e-4045-947d-91e992195518.png)

0. Which image is this commit image dialog affecting? It's unclear, as the title is generic.
1. Can OCI vs. Docker format be switched between commits or change from the original image? The radio buttons here imply that. Also, why isn't one selected by default (the current image format type)? Additionally, the case is "OCI" (an initialism) and "Docker" (a proper noun).
2. Can the image name be changed? Or does it have to be changed versus what is currently used?
3. How many of these fields can be prepopulated with the current values?
4. What is the message? Is it a notes/memo field, where the value doesn't matter, but it's freeform text to explain what changed? How long can it be? (Is it a few words, a sentence, paragraph, or more?)
5. What does pausing and variables have to do with "command"? Right now, the UI implies that they're related. They should be separate fields if they're not related.
6. What does pausing do? Does that affect the container, not the image?
7. What does "set container on build variables" mean? Does it set variables that are used by default when a container is created by this image?
8. Are previously existing variables shown in this commit image dialog?

I can help with the UI once I understand the above a bit better.

**Comment by marusak** [comment]
@garrett You can commit a *container*, not an *image*. Result of committing is an image. So the title should say `Commit container <foo>` I think. I hope that answers most of your questions.
For more info see `man podman commit`.

About pre-populating values - I think that only Command is used from the base image (the one, from which the container was ran). If that is the case, then that would make sense to prefill.

Also I think that message maybe can be dropped, as of:
```
   --message, -m=message
       Set commit message for committed image.
       IMPORTANT: The message field is not supported in oci format.

```

**Comment by garrett** [comment]
> I hope that answers most of your questions.

No, not really. Pretty much all of the points I brought up are still unaddressed. I asked these questions mainly on behalf of the user; they need to be answered in the UI. A few were me asking questions to be answered based on our implementation. (Such as what are we doing with respect to Docker vs. OCI? Can we prefill all these fields with existing values?)

Additionally, we should make it clear that it's saving the container as a new image with some text at the top, similar to PF's ["Create account" modal demo](https://www.patternfly.org/v4/components/modal/html-demos/modal-with-form/), where it says, "_Enter your personal information below to create an account_.":

![image](https://user-images.githubusercontent.com/10246/141760936-131d5291-0ecf-4100-8f75-66d7cd1dac64.png)

We'd say something like: "Create a new image based on the current state of the XYZ container."

> Also I think that message maybe can be dropped, as of:

Are we supporting "Docker" as a format option still? We could toggle the visibility of "Message" based on which format is selected, if so.

**Comment by jelly** [comment]
The [podman man page](https://docs.podman.io/en/latest/markdown/podman-commit.1.html) seems to explain it well. 

I think the Command should be pre-filled if possible, as one can "override it"?

**Comment by marusak** [comment]
>  Which image is this commit image dialog affecting? It's unclear, as the title is generic.

None, it affects container. The title should be changed.

> Can OCI vs. Docker format be switched between commits or change from the original image? The radio buttons here imply that. Also, why isn't one selected by default (the current image format type)? Additionally, the case is "OCI" (an initialism) and "Docker" (a proper noun).

You are committing container to an image - container does not have format. There is also no "between commits". You just need to choose format. It does not matter if the base image was docker or oci - it only matters when you want the new image to be.

> Can the image name be changed? Or does it have to be changed versus what is currently used?

Which image? The one you are going to create? You can always re-tag any image to give it different name. You can also use name of already existing image, but I would say that is very bad practice, especially for the one, from which you ran the container in the first place.

> How many of these fields can be prepopulated with the current values?

I answered this before. Command is kept from container, we can pre-fill that. Format is by default oci, we should do that (now it is buggy, you cannot properly change it), image name cannot (we could do some guess work like name of container, name of base image... but I think user should just pick what they want). Tag is by default `latest`, no need to prefill anything different. Author should not be kept, as your base image can be official distro build and you don't want to pretend it is the same. Message does not make sense to prefill (podman by default puts there `Created by Image Factory`).

> What is the message? Is it a notes/memo field, where the value doesn't matter, but it's freeform text to explain what changed? How long can it be? (Is it a few words, a sentence, paragraph, or more?)

It is only supported for docker type, so it is some obsolete docker thing. It is freeform, nowhere I could find any limitation for length. But it feels like very special use-case that we don;t need to expose in our UI.

> What does pausing and variables have to do with "command"? Right now, the UI implies that they're related. They should be separate fields if they're not related.

Nothing, this is the common issue we have, that checkbox has it's own label, so we don;t give it form label. We need to give it both labels.

> What does pausing do? Does that affect the container, not the image?

It pauses the container, from which you are creating the image.

> What does "set container on build variables" mean? Does it set variables that are used by default when a container is created by this image?

https://docs.docker.com/engine/reference/builder/#onbuild

> Are previously existing variables shown in this commit image dialog?

No.

> Are we supporting "Docker" as a format option still? We could toggle the visibility of "Message" based on which format is selected, if so.

We support it. We should also be toggling the visibility of this field. But now when I tried it, it is broken. When I toggle the top radio, neither value is selected and I cannot select either of them. This got broken.

**Comment by garrett** [comment]
> You are committing container to an image - container does not have format. 

But the image on disk the container is based on has a format, right? That's what I'm talking about.

> There is also no "between commits". 

_This dialog_ is literally between commits from a UI standpoint, which is what I'm talking about:

1. You have an image on disk or network. (First commit)
2. You create a container based on the image. (Which is downloaded, if need be, or used from disk if it exists)
3. You ask Cockpit to create an image based on the container, using a modal dialog. _(We are here)_
4. You have an image on disk. (New commit)

> You just need to choose format. It does not matter if the base image was docker or oci - it only matters when you want the new image to be.

If it doesn't matter, then why don't we have a default? And why not make it the same as what you're basing this on... or just go with OCI?

When would you want OCI and when would you want Docker as a format?

> Which image? The one you are going to create? You can always re-tag any image to give it different name. You can also use name of already existing image, but I would say that is very bad practice, especially for the one, from which you ran the container in the first place.

What is it based on? There's no context.

What happens when you give it the same name? Should that be an error if you choose the same name if it's "very bad practice"?

> It is only supported for docker type, so it is some obsolete docker thing. It is freeform, nowhere I could find any limitation for length. But it feels like very special use-case that we don;t need to expose in our UI.

If it's some obsolete Docker thing, then why are we showing a choice between OCI and Docker, and why isn't OCI set by default if we still want to give someone a choice?

> Command is kept from container, we can pre-fill that. Format is by default oci, we should do that (now it is buggy, you cannot properly change it), image name cannot (we could do some guess work like name of container, name of base image... but I think user should just pick what they want). Tag is by default latest, no need to prefill anything different. Author should not be kept, as your base image can be official distro build and you don't want to pretend it is the same. Message does not make sense to prefill (podman by default puts there Created by Image Factory).

So:

- Default to OCI
- Make the name show an error if it conflicts with an existing image name?
- Make the tag field say that it'll default to latest if it's not filled in?
- Remove message field
- Change "set container on build variables" to "Set ONBUILD variables"
- Split out options to its own group
- Consider [non-expandable field groups](https://www.patternfly.org/v4/components/form#field-groups) for the variables
- Also: Perhaps change the OCI / Docker radio to a "Legacy Docker format" as a checkbox as an option at the end?

**Comment by garrett** [comment]
New mockup for the dialog:

![container-commit-image](https://user-images.githubusercontent.com/10246/141963744-5a857077-d3c7-4d9a-8b97-527e02a7e21d.png)

The fields are different lengths to indicate the expected length of the contents (plus a little more for room). As commands can get long, the field is full width.

It would be _awesome_ to store the author field in the browser's local storage and remember that for the next time around.

When there's a conflict, treat it as an error, but provide a force override to proceed anyway:

![container-commit-image-conflict](https://user-images.githubusercontent.com/10246/141963736-19140c1d-4cf0-4607-833d-0421d1d39dff.png)

I just checked (after making this mockup) and warning buttons actually have darker text. https://www.patternfly.org/v4/components/button#variations — just consider the concept of a warning button (or even a secondary danger button which has a red outline) and not the style in the mockup. :wink: 

Excalidraw file: 
[container-commit-image.zip](https://github.com/cockpit-project/cockpit-podman/files/7545304/container-commit-image.zip)

Read only Excalidraw (although you can change and have it be a new document):
https://excalidraw.com/#json=P30_k7gSVK0EzVIfFex8J,vrIofzNHFaW4Zd5Q20rBiQ

**Comment by garrett** [comment]
Updated: 


![container-commit-image(1)](https://user-images.githubusercontent.com/10246/141969100-a6bed601-beca-4f2f-b2d4-f915c5632aba.png)

![container-commit-image-conflict(1)](https://user-images.githubusercontent.com/10246/141969121-3711a6c7-dffb-41f1-b51f-2f0636b540ad.png)

Changes: 

- Command is now exactly what was used in the container and it's prefilled instead, so it's editable.
- Author has an example
- Re-added pause (whoops!)
- Since there are two options, I went with an "options" group
- I changed the style of the disabled and warning buttons to better reflect PF's style (background / foreground colors)
- I made all fields full width except for tag, which should still be limited with the PF sizing utils https://www.patternfly.org/v4/utilities/sizing (I would suggest ch, but it uses inline styles, so we might need to use the percentage base one, and it should definitely be used with a breakpoint so mobile doesn't get the size limiting, or it gets a larger limit)

- [container-commit-image-revised.zip](https://github.com/cockpit-project/cockpit-podman/files/7545528/container-commit-image-revised.zip)
- https://excalidraw.com/#json=3-8nx_DEkpa8Eio8mIrZc,xpwR33-B0yA1rlo2i2lKkA
