### ISSUE TITLE
show and manage rootless containers

### ISSUE THREAD

**Issue by tabowling** [cockpit-project/cockpit-podman#83]
When I logging in using my regular user account with super priviledges (wheel group) I cannot see or manage container images/instances of that user account.

I can see and manage images/instances of containers owned by root, but not my own.

**Comment by marusak** [comment]
@garrett @andreasn I want to take a look at this but I would need some design ideas how to approach this. Do you have some ideas that I can start working on?

**Comment by garrett** [comment]
We had a discussion about this today. Here's what we agreed upon:

- Call it "User" and "System" containers (as "Session" is problematic)
- Integrate user & system containers in the same list
- Show system containers first in the list, then display user containers
- At least for the first pass, ask podman for both system and user containers at the same time and display the list when both come back (this could possibly be optimized, especially if it takes longer than half a second in total)
- Have a triad filter: all / system / user — the widget for this hasn't been decided (PF4 seems to use a dropdown for filtering lists, but this is more of a mode switcher that affects the whole page)
- When a list is filtered, there was a debate on whether it would affect the create new dialog: 
   - whether it would even show an option or have an option pre-selected
      - (I prefer pre-selection versus hiding the option — imagine someone having both types of containers, filtering to system, and wanting to create a user container — and then missing the option for it)
   - if the type selected differs from the filter, the filter should be reset to show all (so the container doesn't mysteriously "disappear")

Open questions:
- Which widget should we user for the triad filter? (Dropdown, a set of links, tabs, a group of buttons, …)
- Should user or system be called "owner", "scope", or "type"?

**Comment by mailinglists35** [comment]
this only works with my own containers. how do I view all other regular users containers, without logging in and out for each user? I have sudo and on terminal I can view them like this:

````
$ getent passwd | grep bash | grep -Ev 'myself:|root:' | awk -F: '{print $1}'|xargs -Iusername sudo systemd-run --machine=username@ --quiet --user --collect --pipe --wait podman container ps --noheading --no-trunc
````
