### ISSUE TITLE
mobile: Tabs overflow in small sizes

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#845]
![Screen Shot 2021-12-01 at 17 47 20](https://user-images.githubusercontent.com/10246/144276827-71e09ef1-143e-46ba-bcfc-7476ed2abf6b.png)

It's also impossible to see and switch tabs at this sizes.

This is the iPhone 5 / SE size.

**Comment by garrett** [comment]
It's still bad on the iPhone 13 Pro Max size (which is huge)... just not quite as bad, as you can see a little bit of the second tab:

![Screen Shot 2021-12-01 at 17 49 06](https://user-images.githubusercontent.com/10246/144277101-1ab63484-165b-4aca-895e-778fe9b02749.png)

**Comment by garrett** [comment]
(These are the 2x "retina" sizes. Sorry for them being so huge.)

**Comment by jelly** [comment]
I can see the issue, I am not sure how we can improve the situation, do we need to switch to a different component or can we improve the Tab component to be more user friendly?

Should we consider switching to a `vertical` view https://www.patternfly.org/v4/components/tabs#vertical ?

**Comment by garrett** [comment]
No, the vertical one would be even more problematic. This has been an issue with PF for a while. I had an override for tertiary navigation (which looks much like the tabs and was removed in favor of tabs) and had some upstream issues for it and tabs at:

- https://github.com/patternfly/patternfly-design/issues/840
- https://github.com/patternfly/patternfly-design/issues/1034

We'll probably have to do some CSS override to make them wrap here.

**Comment by garrett** [comment]
The fix in #848 helps here, but we could still hit the same issue with longer strings (different languages, when this is translated, as it apparently is not) or more strings (as in more tabs).
