### ISSUE TITLE
There is no way to correctly translate a split string

### ISSUE THREAD

**Issue by piotrdrag** [cockpit-project/cockpit-podman#846]
This: https://github.com/cockpit-project/cockpit-podman/blob/main/src/PruneUnusedImagesModal.jsx#L29 is untranslatable. Please just use two strings with full sentences.

More on why: https://wiki.gnome.org/TranslationProject/DevGuidelines/Never%20split%20sentences

**Comment by martinpitt** [comment]
Heh, this was actually discussed in https://github.com/cockpit-project/cockpit-podman/pull/831#pullrequestreview-813668774

It's borderline of course; however, it does not really split the sentence, but just makes one word variable. This can still go wrong in languages where "user" and "system" have two different grammatical genders in languages. Did you run into such a language?

**Comment by marusak** [comment]
I believe, that any time we are constructing string from two translated substrings, we should not try to make it somewhat universal, but just define each string individually. It is safer, leads to better translations and makes life for translators easier.

**Comment by martinpitt** [comment]
Fair enough. That effectively means "no translated string can ever contain HTML formatting".

**Comment by marusak** [comment]
> That effectively means "no translated string can ever contain HTML formatting".

It can, if the content that is wrapped in the HTML element is not being translated as well. So we can have `Connect to <b>127.0.0.2</b>` as we don't need to translate the `127.0.0.2`, but not `Connect to <b>remote machine</b>`.

**Comment by piotrdrag** [comment]
That’s not exactly the problem here for me, although I’m very much sure there are languages where it would be. The problem is that the string `system` (and possibly `user` in the future) is used in more places than just this one:

```
#: src/Containers.jsx:335 src/Images.jsx:123 src/PruneUnusedImagesModal.jsx:29
#: src/ImageSearchModal.jsx:149
msgid "system"
msgstr ""
```

If I translate it correctly for this use case, it will be incorrect in the other places. You could work around it by using gettext context for the variable: https://wiki.gnome.org/TranslationProject/DevGuidelines/Translation%20contexts but ideally it would just be two strings.
