### ISSUE TITLE
mobile: Images list is broken

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#864]
When the images list is in mobile, it looks like this (on a very large phone even; this is the iPhone 13 Pro Max size):

![image](https://user-images.githubusercontent.com/10246/146195673-c332b817-136f-42ab-9e86-2187d910a85d.png)

This is related to #844, but is additionally even more problematic due to the action button. I suggest reworking the list with the same technique in the (currently yet-to-land) storage page:

- https://github.com/cockpit-project/cockpit/pull/16681

**Comment by mvollmer** [comment]
The code in the storage page is impossible to re-use, unfortunately.  We could factor it out into a reusable component and put it into lib/. Or should we wait for a PF fix?
