### ISSUE TITLE
follow-up to #851: options should come after restart policy

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#876]
Follow-up to #851:

Conceptually, the options (where we currently just have the start on creation) should come after the restart policy. Everything aside from the auto-start is related to container creation itself and affects the container directly. Starting automatically after the container is created is unrelated to all the other items in the dialog.

**TL;DR**: Move "options" section to be the last thing, below the restart policy.

**Comment by garrett** [comment]
It would be nice to get this in before the release. The screenshot would need to be updated (but it needs to be updated anyway).

**Comment by jelly** [comment]
The screenshot in the Pull request is wrong, the Options are shown under Restart Policy https://github.com/cockpit-project/cockpit-podman/blob/main/src/ImageRunModal.jsx#L977
