### ISSUE TITLE
Can't search for images when connect behind corporate proxy

### ISSUE THREAD

**Issue by githubcek** [cockpit-project/cockpit-podman#884]
Podman (command line) is working behind corporate proxy by setting proxy in containers.conf.

In Cockpit-podman it is not possible to search for images when behind proxy :-( 
Or maybe I have forgotten to configure something?

**Comment by jelly** [comment]
Do you set `http_proxy` or `https_proxy` in your cli environment as that might make podman search work behind a proxy. Cockpit-podman uses podman's REST api so does not take that into account.

**Comment by githubcek** [comment]
Thanks. I have set http_proxy and https_proxy env and it didn't help :( 

For example:
```
# podman search buxybox
INDEX       NAME                               DESCRIPTION                                      STARS       OFFICIAL    AUTOMATED
docker.io   docker.io/vinit3004/buxybox                                                         0
docker.io   docker.io/invidian/buxybox                                                          0
docker.io   docker.io/haveli/buxybox                                                            0
docker.io   docker.io/xianchao/buxybox                                                          0
docker.io   docker.io/17621728268/buxybox                                                       0
docker.io   docker.io/britzcontainers/buxybox                                                   0
docker.io   docker.io/dlgzdd/httpd             buxybox httpd                                    0
docker.io   docker.io/jokerjack/httpd          base image:  buxybox, running httpd server, ...  0

```
on cockpit when I search for image I get:
Failed to search for new images

Error message: Failed to search for images: 4 errors occurred: * couldn't search registry "registry.fedoraproject.org": pinging container registry registry.fedoraproject.org: Get "https://registry.fedoraproject.org/v2/": dial tcp 38.145.60.21:443: i/o timeout * couldn't search registry "registry.access.redhat.com": pinging container registry registry.access.redhat.com: Get "https://registry.access.redhat.com/v2/": dial tcp 2.21.172.33:443: i/o timeout * couldn't search registry "registry.centos.org": pinging container registry registry.centos.org: Get "https://registry.centos.org/v2/": dial tcp 35.180.173.132:443: i/o timeout * couldn't search registry "docker.io": pinging container registry index.docker.io: Get "https://index.docker.io/v2/": dial tcp 34.198.0.87:443: i/o timeout 

Is it because it try to ping first? (And ping is not allowed on corporate network?)
```
# ping docker.io -c 1
PING docker.io (34.202.228.80) 56(84) bytes of data.
--- docker.io ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

```
Is it possible to bypass ping in cockpit-podman and try to search anyway?

**Comment by jelly** [comment]
As cockpit-podman uses `podman.service` the user or system service shell set environment variables are not available. What you probably want is to set the the `env` option in `/etc/containers/containers.conf` to something like:

```
# Environment variables to be used when running the container engine (e.g., Podman, Buildah).
# For example "http_proxy=internal.proxy.company.com".
# Note these environment variables will not be used within the container.
# Set the env section under [containers] table, if you want to set environment variables for the container.
#
env = ["http_proxy=http://nonononnon.com", "https_proxy=https://nononononononono.com"]
```

**Comment by pjconnol** [comment]
The only way I was able to get the cockpit-podman search working behind my corporate proxy is the following:

1. Create `podman.service.d` in the systemctl directory:
```bash 
mkdir /etc/systemd/system/podman.service.d`
```
2. Create/open a file called `http-proxy.conf` in `/etc/systemd/system/podman.service.d`:
```bash
vim /etc/systemd/system/podman.service.d/http-proxy.conf
```
3. Add the following into that file (Replacing `` with your own proxy address):
``ìni
[Service]
Environment="HTTP_PROXY=http://proxy.domain.com:889" "HTTPS_PROXY=https://proxy.domain.com:890"
```
4. Reload Podman:
```bash
systemctl daemon-reload
systemctl restart podman
```

The search on the cockpit-podman interface should now work. Hopefully this works for you!
