### ISSUE TITLE
Clicking on container does nothing

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit-podman#89]
When I click on `image` listing-item (the whole line) it expands. However when I click on `container` it does nothing. On containers I need to click on the arrow on the left to make the item expand.

I am not sure which of these two is the right behavior, but they should behave equally. Also on containers is confusing that when I hover on the item it becomes blue, but clicking does nothing. And also containers lines become blue, but images lines become grey on hover.

**Comment by larskarlitski** [comment]
Good catch. We have two kinds of expandable list items:
1. The ones that turn gray on hover. They expand the row on click
2. The ones that turn blue on hover. They lead to a details page when clicked. Some of those can also be expanded, but you need to use the expansion triangle for that.
