### ISSUE TITLE
Download failures of container image not shown

### ISSUE THREAD

**Issue by gbraad** [cockpit-project/cockpit-podman#914]
We are hosting the podman view as a frame, and therefore do not have the `shell` available to us. This might be the problem, but when ewe download an image that is not actually available for the target #913 we aren't informed of a failure.

_Originally posted by @gbraad in https://github.com/code-ready/tray-electron/issues/135#issuecomment-1031566300_

**Comment by jelly** [comment]
What do you mean with `frame` and `shell`? I think the notifications are drawn [inside](https://github.com/cockpit-project/cockpit-podman/blob/65eac9f52912d993e78b1ab5d96ee4cd3f78ef2a/src/app.jsx#L677) cockpit-podman so not something cockpit itself provides.

**Comment by jelly** [comment]
Just setup my RPI with Fedora server, creating a new container and selecting `archlinux` which has no AARCH64 image and it is indeed stuck at showing "Downloading".

`podman ps` and `podman ps -a` shows nothing. Ideally we would filter valid images up front but I'm afraid we lack the information to do so.

**Comment by gbraad** [comment]
👍

**Comment by gbraad** [comment]
In this case, will the download now show an error or just 'finish' downloading?

**Comment by jelly** [comment]
As podman doesn't give error codes, this is the best we can do:

![image](https://user-images.githubusercontent.com/67428/153562901-f7d10abb-528f-45d9-bd33-606c3786b9ff.png)

https://github.com/cockpit-project/cockpit-podman/pull/916

**Comment by gbraad** [comment]
OK, better than nothing. But very UI unfriendly

**Comment by jelly** [comment]
> OK, better than nothing. But very UI unfriendly

I agree, I hope podman can implement optional filtering of architecture then we can use that in cockpit-podman

**Comment by vrothberg** [comment]
Note that I currently do not have time to implement it but [the summary here](https://github.com/containers/podman/issues/13199#issuecomment-1036158966) should give a good starting point on what needs to be done. Again the warning that such client-side filtering can be very slow/expensive. Unfortunately, the search endpoints on registries do not support such filters.
