### ISSUE TITLE
Restart policy not available for non-system users.

### ISSUE THREAD

**Issue by arctic-alpaca** [cockpit-project/cockpit-podman#921]
Cockpit version: 262
Cockpit-podman version: 41
Podman version: 3.4.4
OS: Fedora 35

Hi,
as far as I can tell, the restart policy should be usable as non-system user if `linger` is enabled for that user. This currently isn't the case, only the system user can set a restart policy. When selecting a non-system user, the restart policy drop-down disappears even though `linger` is active.

**Comment by garrett** [comment]
Details:

According to https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html (which is specifically about generate systemd, but should also apply to the restart policy):

> The systemd user instance is killed after the last session for the user is closed. The systemd user instance can be kept running ever after the user logs out by enabling lingering using
>
> ```
> $ loginctl enable-linger <username>
> ```

This brings up the question of whether we should always show it and have it be disabled when it's not supported, with a popover explaining that loginctl enable-linger needs to be run...

OR

We could run `loginctl enable-linger <username>` from within Cockpit if someone enables the restart policy. In this case, if someone selects a restart policy and they don't have linger enabled, we would probably want to message that below the option that linger support will be enabled for the user.

The second of these is better, as Cockpit should handle details like this.

---

To check linger status, a user would be mentioned in `/var/lib/systemd/linger/` if there is linger support. `loginctl show-user "$USER" --property=Linger | grep -q 'yes'` also shows linger status. Details @ https://serverfault.com/questions/846441/loginctl-enable-linger-disable-linger-but-reading-linger-status

**Comment by jelly** [comment]
IIRC @martinpitt  didn't want us to enable lingering for normal users. So the option we have left is checking if lingering is on, and if not showing a popover that it needs to be manually enabled?

**Comment by martinpitt** [comment]
Well, I'm not sure if that's any better -- whether cockpit does it semi-automatically or whether we lure the user into blindly copy&pasting this command, the effect will be the same: It has potentially dangerous and unexpected effects. We'd really need to slap on a big fat warning / documentation (which then nobody reads..)

I still have the opinion that auto-start is something for system containers only, conceptually. User containers are for development and experimentation, not for a reliable production deployment.

**Comment by garrett** [comment]
> User containers are for development and experimentation, not for a reliable production deployment.

Podman developers and various Red Hat blog posts disagree:

https://developers.redhat.com/blog/2020/09/25/rootless-containers-with-podman-the-basics#why_podman_

> Rootless containers are containers that can be created, run, and managed by users without admin rights. Rootless containers have several advantages:
>
> -   They add a new security layer; even if the container engine, runtime, or orchestrator is compromised, the attacker won't gain root privileges on the host.
> -    They allow multiple unprivileged users to run containers on the same machine (this is especially advantageous in [high-performance computing environments](https://www.redhat.com/en/blog/podman-paves-road-running-containerized-hpc-applications-exascale-supercomputers)).
> -    They allow for isolation inside of nested containers.

(Emphasis on the first point.)

Obviously, if the containers cannot be started on reboot, then they're kind of worthless.

But I've seen people requesting rootless for Cockpit Podman specifically for this first point, with a user specifically for a service or group of services that are in a container.

> It has potentially dangerous and unexpected effects. We'd really need to slap on a big fat warning / documentation (which then nobody reads..)

We could add a warning / danger in the popup with an icon and color. But we'd need to be clear what the issues are with linger.

So: What are the issues with linger?

1. Someone could run a long-running process that can re-start across reboots... _if they already have access to the account_.
2. ... what else?

We could also add some level of linger support to the accounts page, even if that "support" would just be simply show that linger is enabled for a user.

**Comment by martinpitt** [comment]
system containers which run as non-root are not really worse -- they have the same UID privilege separation as user containers do. Containers which run as root in the guest are much more dangerous of course, but that's equally true for the system and the user case.

But my bigger concern is that it's incompatible with e.g. encrypted home directories (ecryptfs, systemd-homed), 2FA, or home directories on NFS or similar network mounts (usually needs credentials on login). It will just fail on boot, and conversely, if a user enables lingering in a running session, the user's home dir will still remain accessible even after logout -- thus nullifying the protection. It also has at least a questionable (if not broken) interaction with `KillUserProcesses=yes`. I also really don't like auto-starting user processes/D-Bus services -- each of them is another possibility for leaking user data.

If we only offer this functionality *if* lingering is *already* enabled, then I'm fine with this of course -- then the user already "did the (potential) damage", and knows what they did. But auto-enabling it or providing a button is just too much of a lure IMHO.

**Comment by garrett** [comment]
The goal isn't to necessarily let arbitrary users run arbitrary containers on restart, but to have specific users set up just for the services to run the containers — just like many services might do. For example:

```
systemd-coredump:x:961:961:systemd Core Dumper:/:/usr/sbin/nologin
```

And people famously use this for Apache, etc.

The difference here would be a container (or related containers, like in a pod) inside that user account instead.

Of course, people will probably have a "containers" user that just runs all the containers too. But that would still be a special "user" account.

The point is that admins would set up the "user" accounts and we wouldn't have to bother with ecryptfs, systemd-homed, 2FA, etc. (This would be for _actual_ users with actual home directories and all the interactive things, unless there are users developing containers in a preview/staging model similar to our local forked repos for the website. And in this specific case, they're probably logged in already, so those concerns still shouldn't be an issue.)

---

> If we only offer this functionality if lingering is already enabled, then I'm fine with this of course -- then the user already "did the (potential) damage", and knows what they did. But auto-enabling it or providing a button is just too much of a lure IMHO.

Yes, lets.

But we should at least show how to enable this from within Cockpit, paired with some warning that clearly states any problems with this approach.

Here's a start:

> ⚠ Using linger for auto-starting containers may not work in some circumstances, such as when ecryptfs, systemd-homed, NFS, or 2FA are used on a user account.

This could be at the bottom of that above-mentioned popover.
