### ISSUE TITLE
Cockpit showing n/a for cpu and memory information

### ISSUE THREAD

**Issue by fischer-felix** [cockpit-project/cockpit-podman#954]
Cockpit version: 251.3-1.0.1.el8_5
Cockpit-podman version: 39-1.module+el8.5.0+20494+0311868c
Podman version: 3.4.2
OS: Oralce Linux Server 8.5

Podman containers that are running in user mode do not display memory or cpu information (only show n/a), however containers running as root do report usage.

Steps to reproduce

1. Install podman and cockpit on Oracle Linux 8
2. Run any container *without* sudo
3. Check Podman containers section in cockpit

![Screenshot_2022 04 05_16:30:36](https://user-images.githubusercontent.com/65448408/161777186-45298a5d-73e7-443d-a7b4-c3689a613f5a.png)

**Comment by marusak** [comment]
It is not a bug. It is a way how we deal with the fact that systems that have cgroupsv1 cannot report usage for user containers. This is known limitation from podman side.  Systems with cgroupsv2 show usage also for these containers.
