### ISSUE TITLE
restarting a container while viewing logs disconnects the log viewer

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-podman#970]
Cockpit version: 265
Cockpit-podman version: 265
Podman version: 4.0.2
OS: Fedora Linux 36 Silverblue

Steps to reproduce

1. View logs for a running container
2. Restart the container
3. Log viewer disconnects and does not reconnect

**Comment by marusak** [comment]
Correct. We need to add some listener for when container is started to connect the console. This can happen for various reasons but restarting it in UI is a good reproducer indeed.
